### ISSUE TITLE
表格里面内容控件无法渲染

### ISSUE THREAD

**Issue by koolalex** [Sayi/poi-tl#1009]
<img width="800" alt="image" src="https://github.com/Sayi/poi-tl/assets/7669548/45f2000c-d209-4d79-a890-01b9f78ba79a">
表格里面内容控件无法渲染？？

报错信息如下：
com.deepoove.poi.exception.RenderException: HackLoopTable for {{carInfos}}error: com.deepoove.poi.xwpf.XWPFStructuredDocumentTagContent cannot be cast to org.apache.poi.xwpf.usermodel.XWPFParagraph
	at com.deepoove.poi.plugin.table.LoopRowTableRenderPolicy.render(LoopRowTableRenderPolicy.java:142)
	at com.deepoove.poi.render.processor.DelegatePolicy.invoke(DelegatePolicy.java:45)
	at com.deepoove.poi.render.processor.ElementProcessor.visit(ElementProcessor.java:65)
	at com.deepoove.poi.render.processor.ElementProcessor.visit(ElementProcessor.java:59)
	at com.deepoove.poi.template.run.RunTemplate.accept(RunTemplate.java:64)
	at com.deepoove.poi.render.processor.DocumentProcessor.visit(DocumentProcessor.java:95)
	at com.deepoove.poi.template.run.RunTemplate.accept(RunTemplate.java:64)
	at com.deepoove.poi.render.processor.DocumentProcessor.lambda$process$0(DocumentProcessor.java:59)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.deepoove.poi.render.processor.DocumentProcessor.process(DocumentProcessor.java:59)
	at com.deepoove.poi.render.DefaultRender.renderTemplate(DefaultRender.java:82)
	at com.deepoove.poi.render.DefaultRender.render(DefaultRender.java:64)
	at com.deepoove.poi.XWPFTemplate.render(XWPFTemplate.java:209)
	at org.example.word.WordRenderUtils.render(WordRenderUtils.java:19)
	at org.example.App.main(App.java:42)
Caused by: java.lang.ClassCastException: com.deepoove.poi.xwpf.XWPFStructuredDocumentTagContent cannot be cast to org.apache.poi.xwpf.usermodel.XWPFParagraph
	at com.deepoove.poi.util.TableTools.isInsideTable(TableTools.java:243)
	at com.deepoove.poi.plugin.table.LoopRowTableRenderPolicy.render(LoopRowTableRenderPolicy.java:81)

**Comment by fwk1010** [comment]
表格需要绑定，如` Configure config = Configure.builder().bind("goods", policy).build();`
参考http://deepoove.com/poi-tl/#hack-loop-table
