### ISSUE TITLE
无模板生成的模板，无法直接渲染

### ISSUE THREAD

**Issue by Zrincet** [Sayi/poi-tl#1031]
### Issue description
无模板生成的模板，无法直接渲染
### poi-tl version
1.12.1
### Minimal test code to reproduce the issue

```java
public static void main(String[] args) throws IOException {
    DocumentRenderData data = Documents.of()
            .addParagraph(Paragraphs.of("{{title}}").create())
            .create();
    XWPFTemplate template = XWPFTemplate.create(data);
    template.render(
            new HashMap<String, Object>(){{
                put("title", "Hi, poi-tl Word模板引擎");
            }});
    template.writeAndClose(Files.newOutputStream(Paths.get("template.docx")));
}
```
```
Exception in thread "main" com.deepoove.poi.exception.RenderException: Unable to render template {{var}}
	at com.deepoove.poi.policy.AbstractRenderPolicy.reThrowException(AbstractRenderPolicy.java:87)
	at com.deepoove.poi.policy.AbstractRenderPolicy.render(AbstractRenderPolicy.java:69)
	at com.deepoove.poi.render.processor.DelegatePolicy.invoke(DelegatePolicy.java:45)
	at com.deepoove.poi.render.processor.ElementProcessor.visit(ElementProcessor.java:65)
	at com.deepoove.poi.render.processor.ElementProcessor.visit(ElementProcessor.java:59)
	at com.deepoove.poi.template.run.RunTemplate.accept(RunTemplate.java:64)
	at com.deepoove.poi.render.processor.DocumentProcessor.visit(DocumentProcessor.java:95)
	at com.deepoove.poi.template.run.RunTemplate.accept(RunTemplate.java:64)
	at com.deepoove.poi.render.processor.DocumentProcessor.lambda$process$0(DocumentProcessor.java:59)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.deepoove.poi.render.processor.DocumentProcessor.process(DocumentProcessor.java:59)
	at com.deepoove.poi.render.DefaultRender.renderTemplate(DefaultRender.java:82)
	at com.deepoove.poi.render.DefaultRender.render(DefaultRender.java:64)
	at com.deepoove.poi.XWPFTemplate.render(XWPFTemplate.java:209)
	at cn.hozoy.WordTest.main(WordTest.java:21)
Caused by: org.apache.xmlbeans.impl.values.XmlValueDisconnectedException
	at org.apache.xmlbeans.impl.values.XmlObjectBase.check_orphaned(XmlObjectBase.java:1229)
	at org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTRImpl.sizeOfTArray(CTRImpl.java:275)
	at org.apache.poi.xwpf.usermodel.XWPFRun.setText(XWPFRun.java:359)
	at com.deepoove.poi.xwpf.BodyContainer.clearPlaceholder(BodyContainer.java:209)
	at com.deepoove.poi.config.Configure$ClearHandler.handler(Configure.java:353)
	at com.deepoove.poi.policy.AbstractRenderPolicy.postValidError(AbstractRenderPolicy.java:94)
	at com.deepoove.poi.policy.AbstractRenderPolicy.render(AbstractRenderPolicy.java:60)
	... 13 more
```

**Comment by Sayi** [comment]
当前的机制是需要先生成再读取：

```java
public static XWPFTemplate readNewTemplate(XWPFTemplate template) throws IOException {
        ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
        template.write(byteArrayOutputStream);
        template.close();
        return XWPFTemplate.compile(new ByteArrayInputStream(byteArrayOutputStream.toByteArray()),
                template.getConfig());
    }
```
