### ISSUE TITLE
word里只有一个文本标签{{name}}时，Unable to render template {{name}}

### ISSUE THREAD

**Issue by liuyinshan7536** [Sayi/poi-tl#1054]
我新增一个word模板，里边仅有一个文本标签{{name}}

然后写main方法给name赋值，最终控制台报了异常，示例代码如下：
`

        PoiTlUtil a = new PoiTlUtil();
        // 1、加载本地模板文件
        InputStream template = a.getClass().getClassLoader().getResourceAsStream("templates/demo2.docx");
        // 2、创建模板对象
        XWPFTemplate xwpfTemplate = XWPFTemplate.compile(template).render(new HashMap<>());

        // 用Map填充模板内容 
        Map<String, Object> data = new HashMap<>();
        data.put("name", "John Doe");

        // 渲染模板
        xwpfTemplate.render(data);

        // 保存生成的文档
        FileOutputStream output = new FileOutputStream("output.docx");
        xwpfTemplate.write(output);

        // 清理资源
        output.close();
        xwpfTemplate.close();
        template.close();
`

异常信息：
`
14:40:52.267 [main] INFO com.deepoove.poi.resolver.TemplateResolver - Resolve the document start...
14:40:52.275 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - {
14:40:52.275 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - {name}}
14:40:52.275 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - [Start]:The run position of {{name}} is 0, Offset in run is 0
14:40:52.275 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - [End]:The run position of {{name}} is 1, Offset in run is 6
14:40:52.277 [main] DEBUG com.deepoove.poi.resolver.TemplateResolver - Resolve where text: {{name}}, and create RunTemplate for XWPFRun
14:40:52.286 [main] INFO com.deepoove.poi.resolver.TemplateResolver - Resolve the document end, resolve and create 1 MetaTemplates.
14:40:52.286 [main] INFO com.deepoove.poi.render.DefaultRender - Render template start...
14:40:52.288 [main] INFO com.deepoove.poi.render.processor.LogProcessor - {{name}}
14:40:52.290 [main] INFO com.deepoove.poi.render.processor.DelegatePolicy - Start render Template {{name}}, Sign: , policy:TextRenderPolicy
14:40:52.291 [main] INFO com.deepoove.poi.policy.TextRenderPolicy - The data [null] of the template {{name}} is illegal, will apply error handler [ClearHandler]
14:40:52.295 [main] INFO com.deepoove.poi.render.DefaultRender - Successfully Render template in 7 millis
14:40:52.295 [main] INFO com.deepoove.poi.render.DefaultRender - Render template start...
14:40:52.295 [main] INFO com.deepoove.poi.render.processor.LogProcessor - {{name}}
14:40:52.295 [main] INFO com.deepoove.poi.render.processor.DelegatePolicy - Start render Template {{name}}, Sign: , policy:TextRenderPolicy
Exception in thread "main" com.deepoove.poi.exception.RenderException: Unable to render template {{name}}
	at com.deepoove.poi.policy.AbstractRenderPolicy.reThrowException(AbstractRenderPolicy.java:87)
	at com.deepoove.poi.policy.AbstractRenderPolicy.render(AbstractRenderPolicy.java:69)
	at com.deepoove.poi.render.processor.DelegatePolicy.invoke(DelegatePolicy.java:45)
	at com.deepoove.poi.render.processor.ElementProcessor.visit(ElementProcessor.java:65)
	at com.deepoove.poi.render.processor.ElementProcessor.visit(ElementProcessor.java:59)
	at com.deepoove.poi.template.run.RunTemplate.accept(RunTemplate.java:64)
	at com.deepoove.poi.render.processor.DocumentProcessor.visit(DocumentProcessor.java:95)
	at com.deepoove.poi.template.run.RunTemplate.accept(RunTemplate.java:64)
	at com.deepoove.poi.render.processor.DocumentProcessor.lambda$process$0(DocumentProcessor.java:59)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.deepoove.poi.render.processor.DocumentProcessor.process(DocumentProcessor.java:59)
	at com.deepoove.poi.render.DefaultRender.renderTemplate(DefaultRender.java:82)
	at com.deepoove.poi.render.DefaultRender.render(DefaultRender.java:64)
	at com.deepoove.poi.XWPFTemplate.render(XWPFTemplate.java:209)
`

经验证，只要模板标签行只有标签时就会报错。

1、{{name}}   只有这个报错
2、姓名：{{name}}   这个就不报错
图片{{@img}}和表格{{#table0}}好像都是这样的，标签所在的位置行上只有标签时就报错

[demo2.docx](https://github.com/Sayi/poi-tl/files/12519823/demo2.docx)

**Comment by Sayi** [comment]
do not recall xwpfTemplate render.
