### ISSUE TITLE
感觉poi-tl门槛好高，好难用起来，琢磨几天了java.lang.NoSuchFieldError: Factory

### ISSUE THREAD

**Issue by hubiao1** [Sayi/poi-tl#1070]
`
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>5.2.2</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml-lite</artifactId>
            <version>5.2.2</version>
        </dependency>
        <dependency>
            <groupId>org.apache.xmlbeans</groupId>
            <artifactId>xmlbeans</artifactId>
            <version>5.0.3</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>5.2.2</version>
        </dependency>
        <dependency>
            <groupId>com.deepoove</groupId>
            <artifactId>poi-tl</artifactId>
            <version>1.12.1</version>
        </dependency>
`
一直各位兼容包报错。。。求大神

DEMO 代码
` XWPFTemplate template = XWPFTemplate.compile("src/main/resources/bz_word_template/template.docx").render(
        new HashMap<String, Object>(){{
          put("title", "Hi, poi-tl Word模板引擎");
        }});
    template.writeAndClose(new FileOutputStream("output.docx"));`
报错
`SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Exception in thread "main" java.lang.NoSuchFieldError: Factory
	at org.apache.poi.xwpf.usermodel.XWPFDocument.onDocumentRead(XWPFDocument.java:196)
	at org.apache.poi.ooxml.POIXMLDocument.load(POIXMLDocument.java:169)
	at org.apache.poi.xwpf.usermodel.XWPFDocument.<init>(XWPFDocument.java:159)
	at com.deepoove.poi.xwpf.NiceXWPFDocument.<init>(NiceXWPFDocument.java:100)
	at com.deepoove.poi.xwpf.NiceXWPFDocument.<init>(NiceXWPFDocument.java:96)
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:164)
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:132)
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:89)
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:79)
	at com.xhgk.base.member.service.WordDemo1.main(WordDemo1.java:21)`

**Comment by hubiao1** [comment]
建议作者贴出完整POM MAVEN引用

**Comment by hmycl0820** [comment]
我也遇到了这个问题，这句话有用：poi-tl依赖的apache-poi版本是5.2.2+，如果你的项目引用了低版本，请升级或删除。
