### ISSUE TITLE
Docker部署项目，代码高亮报错，显示非法模版。本地没有问题。

### ISSUE THREAD

**Issue by mfangyuan** [Sayi/poi-tl#1103]
com.deepoove.poi.exception.RenderException: Unable to render template {{codeContent}}
        at com.deepoove.poi.policy.AbstractRenderPolicy.reThrowException(AbstractRenderPolicy.java:87)
        at com.deepoove.poi.policy.AbstractRenderPolicy.render(AbstractRenderPolicy.java:69)
        at com.deepoove.poi.render.processor.DelegatePolicy.invoke(DelegatePolicy.java:45)
        at com.deepoove.poi.render.processor.ElementProcessor.visit(ElementProcessor.java:65)
        at com.deepoove.poi.render.processor.ElementProcessor.visit(ElementProcessor.java:59)
        at com.deepoove.poi.template.run.RunTemplate.accept(RunTemplate.java:64)
        at com.deepoove.poi.render.processor.DocumentProcessor.visit(DocumentProcessor.java:95)
        at com.deepoove.poi.template.run.RunTemplate.accept(RunTemplate.java:64)
        at com.deepoove.poi.render.processor.DocumentProcessor.lambda$process$0(DocumentProcessor.java:59)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at com.deepoove.poi.render.processor.DocumentProcessor.process(DocumentProcessor.java:59)
        at com.deepoove.poi.render.processor.AbstractIterableProcessor.process(AbstractIterableProcessor.java:80)
        at com.deepoove.poi.render.processor.IterableProcessor.next(IterableProcessor.java:161)
        at com.deepoove.poi.render.processor.IterableProcessor.lambda$handleIterable$0(IterableProcessor.java:93)
        at com.deepoove.poi.render.processor.EnvIterator.foreach(EnvIterator.java:33)
        at com.deepoove.poi.render.processor.IterableProcessor.handleIterable(IterableProcessor.java:93)
        at com.deepoove.poi.render.processor.AbstractIterableProcessor.visit(AbstractIterableProcessor.java:48)
        at com.deepoove.poi.render.processor.IterableProcessor.visit(IterableProcessor.java:50)
        at com.deepoove.poi.template.IterableTemplate.accept(IterableTemplate.java:32)
        at com.deepoove.poi.render.processor.DocumentProcessor.visit(DocumentProcessor.java:90)
        at com.deepoove.poi.template.IterableTemplate.accept(IterableTemplate.java:32)
        at com.deepoove.poi.render.processor.DocumentProcessor.lambda$process$0(DocumentProcessor.java:59)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at com.deepoove.poi.render.processor.DocumentProcessor.process(DocumentProcessor.java:59)
        at com.deepoove.poi.render.processor.AbstractIterableProcessor.process(AbstractIterableProcessor.java:80)
        at com.deepoove.poi.render.processor.IterableProcessor.next(IterableProcessor.java:161)
        at com.deepoove.poi.render.processor.IterableProcessor.lambda$handleIterable$0(IterableProcessor.java:93)
        at com.deepoove.poi.render.processor.EnvIterator.foreach(EnvIterator.java:33)
        at com.deepoove.poi.render.processor.IterableProcessor.handleIterable(IterableProcessor.java:93)
        at com.deepoove.poi.render.processor.AbstractIterableProcessor.visit(AbstractIterableProcessor.java:48)
        at com.deepoove.poi.render.processor.IterableProcessor.visit(IterableProcessor.java:50)
        at com.deepoove.poi.template.IterableTemplate.accept(IterableTemplate.java:32)
        at com.deepoove.poi.render.processor.DocumentProcessor.visit(DocumentProcessor.java:90)
        at com.deepoove.poi.template.IterableTemplate.accept(IterableTemplate.java:32)
        at com.deepoove.poi.render.processor.DocumentProcessor.lambda$process$0(DocumentProcessor.java:59)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at com.deepoove.poi.render.processor.DocumentProcessor.process(DocumentProcessor.java:59)
        at com.deepoove.poi.render.processor.AbstractIterableProcessor.handleOnceWithScope(AbstractIterableProcessor.java:75)
        at com.deepoove.poi.render.processor.AbstractIterableProcessor.visit(AbstractIterableProcessor.java:51)
        at com.deepoove.poi.render.processor.IterableProcessor.visit(IterableProcessor.java:50)
        at com.deepoove.poi.template.IterableTemplate.accept(IterableTemplate.java:32)
        at com.deepoove.poi.render.processor.DocumentProcessor.visit(DocumentProcessor.java:90)
        at com.deepoove.poi.template.IterableTemplate.accept(IterableTemplate.java:32)
        at com.deepoove.poi.render.processor.DocumentProcessor.lambda$process$0(DocumentProcessor.java:59)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at com.deepoove.poi.render.processor.DocumentProcessor.process(DocumentProcessor.java:59)
        at com.deepoove.poi.render.DefaultRender.renderTemplate(DefaultRender.java:82)
        at com.deepoove.poi.render.DefaultRender.render(DefaultRender.java:64)
        at com.deepoove.poi.XWPFTemplate.render(XWPFTemplate.java:209)
        at com.feysh.corax.module.scan.service.reports.ReportsServiceImpl.taskExportRenderWord(ReportsServiceImpl.java:760)
        at com.feysh.corax.module.scan.service.reports.ReportsServiceImpl.taskExportWord(ReportsServiceImpl.java:694)
        at com.feysh.corax.module.scan.service.reports.ReportsServiceImpl.lambda$getTaskExportReport$13(ReportsServiceImpl.java:627)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.IllegalArgumentException: Illegal highlight theme:poitl
        at com.deepoove.poi.plugin.highlight.converter.ParagraphRenderer.<init>(ParagraphRenderer.java:62)
        at com.deepoove.poi.plugin.highlight.converter.HighlightToDocumentRenderDataConverter$1.create(HighlightToDocumentRenderDataConverter.java:43)
        at com.codewaves.codehighlight.core.Highlighter.highlight(Highlighter.java:128)
        at com.deepoove.poi.plugin.highlight.converter.HighlightToDocumentRenderDataConverter.convert(HighlightToDocumentRenderDataConverter.java:50)
        at com.deepoove.poi.plugin.highlight.converter.HighlightToDocumentRenderDataConverter.convert(HighlightToDocumentRenderDataConverter.java:34)
        at com.deepoove.poi.policy.AbstractDocumentConverterRenderPolicy.doRender(AbstractDocumentConverterRenderPolicy.java:46)
        at com.deepoove.poi.policy.AbstractRenderPolicy.render(AbstractRenderPolicy.java:66)
        ... 57 common frames omitted
Caused by: java.lang.NullPointerException: Cannot invoke "java.io.InputStream.read(byte[])" because "input" is null
        at org.apache.commons.compress.utils.IOUtils.copy(IOUtils.java:95)
        at org.apache.commons.compress.utils.IOUtils.copy(IOUtils.java:70)
        at org.apache.commons.compress.utils.IOUtils.toByteArray(IOUtils.java:255)
        at com.deepoove.poi.util.ResourceLoader.loadContent(ResourceLoader.java:29)
        at com.deepoove.poi.plugin.highlight.converter.StylesheetParser.parse(StylesheetParser.java:39)
        at com.deepoove.poi.plugin.highlight.converter.ParagraphRenderer.<init>(ParagraphRenderer.java:58)
        ... 63 common frames omitted

**Comment by Sayi** [comment]
无法重现。
