### ISSUE TITLE
如果两个标签连在一起会导致生成文档错误

### ISSUE THREAD

**Issue by 253936563** [Sayi/poi-tl#111]
比如{测试一}申请{测试二}测试三，那替换的标签会变成{测试一}申请{测试二}

**Comment by Sayi** [comment]
麻烦给个测试用例吧

**Comment by jarWorker** [comment]
**也发现这种情况。**
创建1.docx中只有{{title}}标签

## 测试用例
````package jjapply.test;


import java.io.FileOutputStream;
import java.io.OutputStream;
import java.util.HashMap;
import com.deepoove.poi.XWPFTemplate;


public class Test {
	
	@org.junit.Test
	public void testXWPFTemplate() throws Exception{
		StringBuffer sb =new StringBuffer();
		for (int i = 0; i < 5; i++) {
			String info="姓名{{name"+i+"}}，年龄：{{age"+i+"}}。";
			sb.append(info).append("\n");
		}
		String Info=sb.toString();
		System.out.println("Info=="+Info);
		XWPFTemplate templateRule = XWPFTemplate.compile("E:\\1.docx").render(new HashMap<String, Object>() {
			{
				put("title", Info);
			}

		});
		
		OutputStream outRule = new FileOutputStream("E:\\2.docx");
		templateRule.write(outRule);
		outRule.flush();
		outRule.close();
		templateRule.close();
		XWPFTemplate template = XWPFTemplate.compile("E:\\2.docx").render(new HashMap<String, Object>() {
			{
				for (int j = 0; j < 5; j++) {
					put("name"+j, "测试姓名");
					put("age"+j, "测试年龄");
				}
				
			}

		});
		
		OutputStream out = new FileOutputStream("E:\\2.docx");
		template.write(out);
		out.flush();
		out.close();
		template.close();
		
	}
	
}
````
## 错误信息
>java.lang.StringIndexOutOfBoundsException: String index out of range: 15
	at java.lang.String.substring(String.java:1951)
	at com.deepoove.poi.resolver.TemplateResolver.mergeRuns(TemplateResolver.java:277)
	at com.deepoove.poi.resolver.TemplateResolver.parseRun(TemplateResolver.java:151)
	at com.deepoove.poi.resolver.TemplateResolver.parseParagraph(TemplateResolver.java:102)
	at com.deepoove.poi.resolver.TemplateResolver.parseElementTemplates(TemplateResolver.java:70)
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:131)
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:110)
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:78)
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:74)
	at jjapply.test.Test.testXWPFTemplate(Test.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)


## 控制台输出
>Info==姓名{{name0}}，年龄：{{age0}}。
姓名{{name1}}，年龄：{{age1}}。
姓名{{name2}}，年龄：{{age2}}。
姓名{{name3}}，年龄：{{age3}}。
姓名{{name4}}，年龄：{{age4}}。

**Comment by Sayi** [comment]
多个标签在一起单元测试用例是有的，能正确运行。

@jarWorker 你这个属于一种特殊情况下产生的BUG，我会在下个版本修复。

**Comment by Sayi** [comment]
创建模板的时候使用了换行符导致，这个换行符和模板在一起作为新的模板有点难处理了。

**Comment by DANCERINKEY** [comment]
> 创建模板的时候使用了换行符导致，这个换行符和模板在一起作为新的模板有点难处理了。

请问这个问题解决了吗，我也遇到这个问题

**Comment by WangShaoYang** [comment]
我也碰到相同的问题了，我的模板不是固定的，我希望用代码控制生成模板，比如向{{key}}  传一个  "{{+key1}}\n{{+key2}}\n{{+key3}}"然后模板里面就有{{+key1}}\n{{+key2}}\n{{+key3}}了，再跑一个程序把key1，key2，key3填充上具体的内容。
问题出在\n上，\n不是真正的换行符。
![image](https://user-images.githubusercontent.com/26501618/58468288-dbc53c00-816f-11e9-8ffd-612751f3b066.png)
上图中，↓就不是真正的换行符，会出问题。

**Comment by Sayi** [comment]
下一个版本差不多结束了，这个问题遇到的人还是有不少的，下下个版本我会修复它!!!
