### ISSUE TITLE
报告中图表生成报错：SAXParseException: Premature end of file.

### ISSUE THREAD

**Issue by c1105590204** [Sayi/poi-tl#1131]
### Issue description (Required*) 
报告中使用了曲线图，组装数据后生成报错Caused by: org.xml.sax.SAXParseException: Premature end of file.
之前用同样的方法，类似的报告，可以生成成功
### poi-tl version (Required*) 
1.9.1
### Minimal test code to reproduce the issue (Required*) 

```java
List<TDataDeviceWarnSeeVo> tDataDeviceWarnSeeVos = CollUtil.newArrayList(
                            new TDataDeviceWarnSeeVo(1709284527002L, 10.0),
                            new TDataDeviceWarnSeeVo(1709284528002L, 11.0),
                            new TDataDeviceWarnSeeVo(1709284529002L, 12.0)
                    );
                    if (CollUtil.isNotEmpty(tDataDeviceWarnSeeVos)) {
                        for (TDataDeviceWarnSeeVo tDataDeviceWarnSeeVo : tDataDeviceWarnSeeVos) {
                            times.add(DateUtil.format(tDataDeviceWarnSeeVo.getDate(), chartDateFormat));
                            values.add(tDataDeviceWarnSeeVo.getCalcData());
                        }
                    }
                    Charts.ChartMultis chartMultis = Charts
                            .ofMultiSeries(record.getPointNo() + basDeviceHistoryV2ItemDataVo.getMeasureParamName() + "曲线图", times.toArray(new String[0]));
                    chartMultis.addSeries("values", values.toArray(new Double[0]));
                    ChartMultiSeriesRenderData chartMultiSeriesRenderData = chartMultis.create();
                    chatVo.setData(chartMultiSeriesRenderData);
```

### Minimal Docx template file (Required*) 
[测试模板.docx](https://github.com/Sayi/poi-tl/files/14459230/default.docx)

**Comment by c1105590204** [comment]
异常：com.deepoove.poi.exception.RenderException: Cannot render docx template, please check the Exception
        at com.deepoove.poi.render.DefaultRender.render(DefaultRender.java:69)
        at com.deepoove.poi.XWPFTemplate.render(XWPFTemplate.java:127)
        at com.cmct.iot.tenant.rpc.impl.TenantDubboServiceImpl.crtV3Report(TenantDubboServiceImpl.java:733)
        at com.cmct.iot.tenant.rpc.impl.TenantDubboServiceImpl.fastBuildV3Report(TenantDubboServiceImpl.java:693)
        at com.cmct.iot.tenant.rpc.impl.TenantDubboServiceImpl$$FastClassBySpringCGLIB$$2df2dd28.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at io.seata.spring.annotation.GlobalTransactionalInterceptor.invoke(GlobalTransactionalInterceptor.java:181)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at com.cmct.iot.tenant.rpc.impl.TenantDubboServiceImpl$$EnhancerBySpringCGLIB$$57be8eea.fastBuildV3Report(<generated>)
        at com.cmct.iot.tenant.api.project.BasicProjectStructController.fastBuildReport(BasicProjectStructController.java:715)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1070)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:645)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at com.cmct.iot.web.filter.AbstractApiPermissionCheckFilter.doFilterInternal(AbstractApiPermissionCheckFilter.java:31)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at com.cmct.iot.web.filter.AbstractTokenBasedAuthFilter.doFilterInternal(AbstractTokenBasedAuthFilter.java:31)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:750)
Caused by: org.apache.poi.ooxml.POIXMLException: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at org.apache.poi.ooxml.POIXMLDocumentPart.createRelationship(POIXMLDocumentPart.java:630)
        at com.deepoove.poi.xwpf.NiceXWPFDocument.addChartData(NiceXWPFDocument.java:253)
        at com.deepoove.poi.render.processor.DrawingSupport.processCTGraaphicalObject(DrawingSupport.java:118)
        at com.deepoove.poi.render.processor.DrawingSupport.processCTDrawing(DrawingSupport.java:97)
        at com.deepoove.poi.render.processor.DrawingSupport.updateDocPrId(DrawingSupport.java:71)
        at java.util.ArrayList.forEach(ArrayList.java:1259)
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082)
        at com.deepoove.poi.render.processor.DrawingSupport.updateDocPrId(DrawingSupport.java:63)
        at com.deepoove.poi.render.processor.DrawingSupport.updateDocPrId(DrawingSupport.java:58)
        at com.deepoove.poi.render.processor.IterableProcessor.next(IterableProcessor.java:131)
        at com.deepoove.poi.render.processor.AbstractIterableProcessor.foreach(AbstractIterableProcessor.java:89)
        at com.deepoove.poi.render.processor.IterableProcessor.handleIterable(IterableProcessor.java:93)
        at com.deepoove.poi.render.processor.AbstractIterableProcessor.visit(AbstractIterableProcessor.java:53)
        at com.deepoove.poi.render.processor.IterableProcessor.visit(IterableProcessor.java:50)
        at com.deepoove.poi.template.IterableTemplate.accept(IterableTemplate.java:32)
        at com.deepoove.poi.render.processor.DocumentProcessor.visit(DocumentProcessor.java:89)
        at com.deepoove.poi.template.IterableTemplate.accept(IterableTemplate.java:32)
        at com.deepoove.poi.render.processor.DocumentProcessor.lambda$process$0(DocumentProcessor.java:58)
        at java.util.ArrayList.forEach(ArrayList.java:1259)
        at com.deepoove.poi.render.processor.DocumentProcessor.process(DocumentProcessor.java:58)
        at com.deepoove.poi.render.processor.AbstractIterableProcessor.process(AbstractIterableProcessor.java:103)
        at com.deepoove.poi.render.processor.IterableProcessor.next(IterableProcessor.java:161)
        at com.deepoove.poi.render.processor.AbstractIterableProcessor.foreach(AbstractIterableProcessor.java:89)
        at com.deepoove.poi.render.processor.IterableProcessor.handleIterable(IterableProcessor.java:93)
        at com.deepoove.poi.render.processor.AbstractIterableProcessor.visit(AbstractIterableProcessor.java:53)
        at com.deepoove.poi.render.processor.IterableProcessor.visit(IterableProcessor.java:50)
        at com.deepoove.poi.template.IterableTemplate.accept(IterableTemplate.java:32)
        at com.deepoove.poi.render.processor.DocumentProcessor.visit(DocumentProcessor.java:89)
        at com.deepoove.poi.template.IterableTemplate.accept(IterableTemplate.java:32)
        at com.deepoove.poi.render.processor.DocumentProcessor.lambda$process$0(DocumentProcessor.java:58)
        at java.util.ArrayList.forEach(ArrayList.java:1259)
        at com.deepoove.poi.render.processor.DocumentProcessor.process(DocumentProcessor.java:58)
        at com.deepoove.poi.render.processor.AbstractIterableProcessor.process(AbstractIterableProcessor.java:103)
        at com.deepoove.poi.render.processor.IterableProcessor.next(IterableProcessor.java:161)
        at com.deepoove.poi.render.processor.AbstractIterableProcessor.foreach(AbstractIterableProcessor.java:89)
        at com.deepoove.poi.render.processor.IterableProcessor.handleIterable(IterableProcessor.java:93)
        at com.deepoove.poi.render.processor.AbstractIterableProcessor.visit(AbstractIterableProcessor.java:53)
        at com.deepoove.poi.render.processor.IterableProcessor.visit(IterableProcessor.java:50)
        at com.deepoove.poi.template.IterableTemplate.accept(IterableTemplate.java:32)
        at com.deepoove.poi.render.processor.DocumentProcessor.visit(DocumentProcessor.java:89)
        at com.deepoove.poi.template.IterableTemplate.accept(IterableTemplate.java:32)
        at com.deepoove.poi.render.processor.DocumentProcessor.lambda$process$0(DocumentProcessor.java:58)
        at java.util.ArrayList.forEach(ArrayList.java:1259)
        at com.deepoove.poi.render.processor.DocumentProcessor.process(DocumentProcessor.java:58)
        at com.deepoove.poi.render.DefaultRender.renderTemplate(DefaultRender.java:82)
        at com.deepoove.poi.render.DefaultRender.render(DefaultRender.java:64)
        ... 80 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.deepoove.poi.xwpf.XWPFChartFactory.newDocumentPart(XWPFChartFactory.java:34)
        at org.apache.poi.ooxml.POIXMLDocumentPart.createRelationship(POIXMLDocumentPart.java:615)
        ... 125 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.deepoove.poi.xwpf.XWPFChartFactory.newDocumentPart(XWPFChartFactory.java:32)
        ... 126 common frames omitted
Caused by: org.apache.xmlbeans.XmlException: error: Premature end of file.
        at org.apache.xmlbeans.impl.store.Locale$SaxLoader.load(Locale.java:3448)
        at org.apache.xmlbeans.impl.store.Locale.parseToXmlObject(Locale.java:1272)
        at org.apache.xmlbeans.impl.store.Locale.parseToXmlObject(Locale.java:1259)
        at org.apache.xmlbeans.impl.schema.SchemaTypeLoaderBase.parse(SchemaTypeLoaderBase.java:345)
        at org.openxmlformats.schemas.drawingml.x2006.chart.ChartSpaceDocument$Factory.parse(Unknown Source)
        at org.apache.poi.xddf.usermodel.chart.XDDFChart.<init>(XDDFChart.java:155)
        at org.apache.poi.xwpf.usermodel.XWPFChart.<init>(XWPFChart.java:75)
        ... 131 common frames omitted
Caused by: org.xml.sax.SAXParseException: Premature end of file.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:178)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:399)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:326)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1466)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:1013)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:601)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:642)
        at org.apache.xmlbeans.impl.store.Locale$SaxLoader.load(Locale.java:3422)

**Comment by c1105590204** [comment]
@Sayi Thank求帮助！

**Comment by Sayi** [comment]
请尝试使用最新版：https://deepoove.com/poi-tl/#_%E7%89%88%E6%9C%AC
