### ISSUE TITLE
在输出的下一行提示个错误org.apache.poi.xwpf.usermodel.XWPFRun.getParent()Lorg/apache/poi/xwpf/usermodel/IRunBody;

### ISSUE THREAD

**Issue by ljg20008** [Sayi/poi-tl#117]
//构造数据
        def datas = SgzFormCo03.findAllBySgzFormsAllId(params.sgzFormsAllId);
        def record = SgzFormCo03Record.findAllBySgzFormCo03Id(datas[0].id);
        def name="社区组织登记表";
        def name_file="sgzFormCo03.docx";
        def templatesPath = servletContext.getRealPath('/templates');
        RowRenderData header = RowRenderData.build(new TextRenderData("FFFFFF", "姓名"),
                                                    new TextRenderData("FFFFFF","性别"),
                                                    new TextRenderData("FFFFFF","年龄"),
                                                    new TextRenderData("FFFFFF","联系方式"),
                                                    new TextRenderData("FFFFFF","住址"),
                                                    new TextRenderData("FFFFFF","身份证号"),
                                                    new TextRenderData("FFFFFF","备注"));
        Map<String, Object> datas2 = new HashMap<String, Object>(){{
            put("organizeName", datas[0].organizeName);
            put("server", datas[0].server);
            for (int i=0;i<record.size();i++){
                put("table1", new MiniTableRenderData(header, Arrays.asList(RowRenderData.build("${i+1}"/*,
                        "${record[i].rname}",
                        "${record[i].rsex}",
                        "${record[i].rage}",
                        "${record[i].rphone}",
                        "${record[i].raddress}",
                        "${record[i].ridCard}",
                        "${record[i].rremark}"*/))));
            }
        }};

        //输出
        XWPFTemplate doc = XWPFTemplate.compile("${templatesPath}/${name_file}").render(datas2);
        def downloadFileName = encodeFileName("${name}.docx");
        response.setContentType('application/vnd.ms-word.document.12');
        response.setHeader('content-disposition', "attachment;filename=${downloadFileName}");
        doc.write(response.outputStream);
        response.outputStream.flush();
        response.outputStream.close();
        doc.close();

**Comment by Sayi** [comment]
把具体错误发出来，可能是项目中poi包的版本有冲突。

**Comment by ljg20008** [comment]
麻烦你查看下啊，谢谢！下面是错误信息
errors.GrailsExceptionResolver NoSuchMethodError occurred when processing request: [POST] /imc_4.0_sggl/sgzFormCo03/sgzFormCo03 - parameters:
sgzFormsAllId: 4
org.apache.poi.xwpf.usermodel.XWPFRun.getParent()Lorg/apache/poi/xwpf/usermodel/IRunBody;. Stacktrace follows:
org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Executing action [sgzFormCo03] of controller [plugin.krs.SgzFormCo03Controller] in plugin [plugin-krs] caused exception: Runtime error executing action
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
Caused by: org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Runtime error executing action
	... 3 more
Caused by: java.lang.reflect.InvocationTargetException
	... 3 more
Caused by: java.lang.NoSuchMethodError: org.apache.poi.xwpf.usermodel.XWPFRun.getParent()Lorg/apache/poi/xwpf/usermodel/IRunBody;
	at com.deepoove.poi.NiceXWPFDocument.insertNewTable(NiceXWPFDocument.java:155)
	at com.deepoove.poi.policy.MiniTableRenderPolicy.createTableWithHeaders(MiniTableRenderPolicy.java:96)
	at com.deepoove.poi.policy.MiniTableRenderPolicy.render(MiniTableRenderPolicy.java:85)
	at com.deepoove.poi.policy.SimpleTableRenderPolicy.render(SimpleTableRenderPolicy.java:61)
	at com.deepoove.poi.render.RenderAPI.render(RenderAPI.java:125)
	at com.deepoove.poi.XWPFTemplate.render(XWPFTemplate.java:154)
	at plugin.krs.SgzFormCo03Controller$$ER497WKM.sgzFormCo03(SgzFormCo03Controller.groovy:72)
	... 3 more

**Comment by Sayi** [comment]
apache poi版本需要3.16+，你项目中还引用了一个老版本的poi。

**Comment by Sayi** [comment]
很明显包冲突，在插入表格的时候。
```
Caused by: java.lang.NoSuchMethodError: org.apache.poi.xwpf.usermodel.XWPFRun.getParent()Lorg/apache/poi/xwpf/usermodel/IRunBody;
at com.deepoove.poi.NiceXWPFDocument.insertNewTable(NiceXWPFDocument.java:155)
```

**Comment by ljg20008** [comment]
嗯嗯，那我再换着看看，谢谢啊

**Comment by ljg20008** [comment]
![image](https://user-images.githubusercontent.com/33144687/45793619-9b025280-bcc5-11e8-965d-7a2e02cb5cb5.png) 请问下单选多选这种的如何操作

**Comment by Sayi** [comment]
单选多选需要自己通过poi实现插件
