### ISSUE TITLE
java poi 生成文档 作为模板渲染问题

### ISSUE THREAD

**Issue by dlmu-lq** [Sayi/poi-tl#154]
使用poi先生成一篇文档：在其中写一个融合别的模板的标签；
    
        `
        XWPFDocument document = new XWPFDocument();

        CTDocument1 doc = document.getDocument();
        XWPFParagraph para = document.createParagraph();
        XWPFRun run = para.createRun();
        run.setText(“{{+moudle1}}”);
        run.addCarriageReturn();

        File mainDoc = new File(orderStr +".docx");
        if(!mainDoc.exists())
            mainDoc.createNewFile();
        BufferedOutputStream fos = new BufferedOutputStream(new FileOutputStream(mainDoc));
        document.write(fos);
        fos.close();
 `
再渲染上面这篇文档，报错：
        `java.lang.NullPointerException: null
	at com.deepoove.poi.NiceXWPFDocument.mergeStyles(NiceXWPFDocument.java:581) [poi-tl-1.4.0.jar:?]
	at com.deepoove.poi.NiceXWPFDocument.extractMergePart(NiceXWPFDocument.java:481) [poi-tl-1.4.0.jar:?]
	at com.deepoove.poi.NiceXWPFDocument.merge(NiceXWPFDocument.java:437) [poi-tl-1.4.0.jar:?]
	at com.deepoove.poi.policy.DocxRenderPolicy.doRender(DocxRenderPolicy.java:56) [poi-tl-1.4.0.jar:?]
	at com.deepoove.poi.policy.AbstractRenderPolicy.render(AbstractRenderPolicy.java:51) [poi-tl-1.4.0.jar:?]
	at com.deepoove.poi.render.RenderAPI.doRender(RenderAPI.java:103) [poi-tl-1.4.0.jar:?]
	at com.deepoove.poi.render.RenderAPI.render(RenderAPI.java:90) [poi-tl-1.4.0.jar:?]
	at com.deepoove.poi.XWPFTemplate.render(XWPFTemplate.java:156) [poi-tl-1.4.0.jar:?]
	at 

但是将poi先生成的文档使用word 2013打开，回车，保存，再作为模板渲染就一切正常。

**Comment by Sayi** [comment]
#149  和这个是一个问题，现在的主模板必须是手动创建的。

**Comment by dlmu-lq** [comment]
暂时的不太优雅的解决方案：
     先手动创建一个文档保存，再用poi操作此文档产生自己想要的可以渲染的主模板，可以使用；
     但是我使用时出现了其他一些问题：如页眉页脚无法渲染；
     仍然在解决，希望大家有解决方案的不吝分享；

**Comment by Sayi** [comment]
你试试最新版本1.4.2,如果还有问题，可以提出来看看
