### ISSUE TITLE
java 1.8, eclipse, poi 3.16

### ISSUE THREAD

**Issue by greatlse** [Sayi/poi-tl#184]
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/poi/xwpf/usermodel/XWPFDocument
	at com.wuxiapptec.wordTemp.COA.main(COA.java:11)
Caused by: java.lang.ClassNotFoundException: org.apache.poi.xwpf.usermodel.XWPFDocument
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

**Comment by Sayi** [comment]
poi3.16 包没有引入成功吧
