### ISSUE TITLE
往wps word中插入图片报错

### ISSUE THREAD

**Issue by Anthony-Lu** [Sayi/poi-tl#205]
您好，麻烦能帮忙看下吗？
12:47:30.631 [main] WARN com.deepoove.poi.resolver.RunningRunParagraph - found the empty text run,may be produce bug:
Exception in thread "main" java.lang.NullPointerException
at com.deepoove.poi.resolver.RunningRunParagraph.refactorRun(RunningRunParagraph.java:65)

12:47:30.633 [main] DEBUG com.deepoove.poi.resolver.RunningRunParagraph - [LEFT]:段落内第0个run,标签为{{@img}}, 在这个run内的边界位置为：0
12:47:30.633 [main] DEBUG com.deepoove.poi.resolver.RunningRunParagraph - [RIGHT]:段落内第0个run,标签为{{@img}}, 在这个run内的边界位置为：0

**Comment by Anthony-Lu** [comment]
Exception in thread "main" java.lang.NullPointerException
	at com.deepoove.poi.resolver.RunningRunParagraph.refactorRun(RunningRunParagraph.java:65)
	at com.deepoove.poi.resolver.TemplateVisitor.visitParagraph(TemplateVisitor.java:132)
	at com.deepoove.poi.resolver.TemplateVisitor.visitParagraphs(TemplateVisitor.java:99)
	at com.deepoove.poi.resolver.TemplateVisitor.visitDocument(TemplateVisitor.java:70)
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:132)
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:111)
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:79)
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:75)
	at com.xykj.koala.util.WordUtils.testNumbericRender(WordUtils.java:46)
	at com.xykj.koala.util.WordUtils.main(WordUtils.java:31)
12:52:44.018 [main] WARN com.deepoove.poi.resolver.RunningRunParagraph - found the empty text run,may be produce bug:
{{@img}}

12:52:44.021 [main] DEBUG com.deepoove.poi.resolver.RunningRunParagraph - [LEFT]:段落内第0个run,标签为{{@img}}, 在这个run内的边界位置为：0
12:52:44.021 [main] DEBUG com.deepoove.poi.resolver.RunningRunParagraph - [RIGHT]:段落内第0个run,标签为{{@img}}, 在这个run内的边界位置为：0

**Comment by Sayi** [comment]
found the empty text run,may be produce bug

@img 段落有些字符有问题，可以把能重现这个BUG的模板发给我。

**Comment by Sayi** [comment]
@Anthony-Lu 把自定义图形 都改成表格布局

表格基本上可以实现所有专业布局效果~

**Comment by Anthony-Lu** [comment]
@Sayi 嗯~那个模板是ui设计好的pdf格式，我拿到后转回了word，然后在word中操作替换值的。
