### ISSUE TITLE
XWPFTemplate render(Object model)异常没有往外抛，只是有打印出来

### ISSUE THREAD

**Issue by xinhaiCai** [Sayi/poi-tl#212]
像这样业务层拿不到异常默认会当做成功处理，生产上是有问题的

`2019-04-04 10:14:53,592 ERROR com.deepoove.poi.el.Dot (main:[]) 90 Connot find the key:exchangePlanPower from Prefix-Model EL:null
2019-04-04 10:14:54,667 ERROR com.deepoove.poi.policy.DynamicTableRenderPolicy (main:[]) 59 dynamic table error:null
java.lang.NullPointerException: null
	at com.deepoove.poi.util.TableTools.mergeCellsVertically(TableTools.java:74) ~[poi-tl-1.4.2.jar:?]
	at com.pmpr.background.poi.DetailTablePolicy.render(DetailTablePolicy.java:41) ~[classes/:?]
	at com.deepoove.poi.policy.DynamicTableRenderPolicy.render(DynamicTableRenderPolicy.java:57) [poi-tl-1.4.2.jar:?]
	at com.deepoove.poi.render.RenderAPI.doRender(RenderAPI.java:103) [poi-tl-1.4.2.jar:?]
	at com.deepoove.poi.render.RenderAPI.render(RenderAPI.java:72) [poi-tl-1.4.2.jar:?]
	at com.deepoove.poi.XWPFTemplate.render(XWPFTemplate.java:156) [poi-tl-1.4.2.jar:?]
`

**Comment by Sayi** [comment]
谢谢建议，有些异常的确应该考虑抛出去，下个版本我会修复下。
