### ISSUE TITLE
让 poi-tl 支持Android

### ISSUE THREAD

**Issue by zwc456baby** [Sayi/poi-tl#227]
建议这个库推出一个针对 android 的版本，这样可以让用户更简单的集成 poi-tl。

下面是让 Android 支持poi-tl 的操作：

[Android 平台使用 poi-tl 填充生成 world 文件](https://www.jianshu.com/p/60bfb892d42e)

这是我自己做的操作，已经可以正确的填充模板了。

**Comment by zwc456baby** [comment]
突然发现简书锁定文章，直接把内容复制到这里了 


## Android 使用 Poi 生成 World 文件

在 Android 平台中，如果直接导入并使用 poi 会直接无法编译

如果要使用原生的 poi，推荐看看这个 (issues)[[https://stackoverflow.com/questions/34644528/getting-noclassdeffounderrorfailed-resolution-of-ljavax-xml-stream-xmleventfac](https://stackoverflow.com/questions/34644528/getting-noclassdeffounderrorfailed-resolution-of-ljavax-xml-stream-xmleventfac)
]

作者编译了一个 库，直接导入这个 jar 就可以使用了
这是 [作者仓库]([https://github.com/centic9/poi-on-android](https://github.com/centic9/poi-on-android)
)

但是我想使用 `poi-tl` ，因为它可以直接使用模板填充，完全满足我目前的工作需求。

## Android 使用 poi-tl 填充生成 world 文件
[poi-tl 官网](http://deepoove.com/poi-tl/)

[使用 poi-tl 填充 world 入门](http://deepoove.com/poi-tl/#_2min%E5%85%A5%E9%97%A8)

如果直接按照官网的操作，使用 gradle 导入
```
compile group: 'com.deepoove', name: 'poi-tl', version: '1.4.2'
```
这样是无法编译的。解决方法

采用这样的方式导入,在 `build.gradle` 中
```
implementation('com.deepoove:poi-tl:1.4.2') {
        //在Android 中 poi-tl 所依赖的库会导致无法编译
        //所以只使用 poi-tl 的填充功能
        //然后使用其他作者提供的 poi
        //下面是过滤掉 poi-tl 的依赖库
        exclude group: 'org.apache.xmlbeans', module: 'xmlbeans'
        exclude group: 'org.apache.poi', module: 'poi-ooxml'
        exclude group: 'org.apache.poi', module: 'poi-ooxml-schemas'
        exclude group: 'org.apache.poi', module: 'poi'
    }
```
主要是下面的 `exclude` ，把`poi-tl` 的依赖全部取消掉，然后到[这个仓库]([https://github.com/centic9/poi-on-android](https://github.com/centic9/poi-on-android)
)下载可用的 `jar` 包

也可以 [点击直接下载 jar 包](https://github.com/centic9/poi-on-android/releases/download/0.5/poishadow-all.jar)


放入这个 jar 包到app工程的 libs 中，然后在 build.gradle 文件中
```
    implementation files('libs/poishadow-all.jar')
```

至此已经添加好了依赖库，还有最后一步操作,执行下面的操作

**(你可以在 onCreate 前，或者初始化的时候执行它，但必须保证是在使用 poi 前)**
```
System.setProperty("org.apache.poi.javax.xml.stream.XMLInputFactory", "com.fasterxml.aalto.stax.InputFactoryImpl");
System.setProperty("org.apache.poi.javax.xml.stream.XMLOutputFactory", "com.fasterxml.aalto.stax.OutputFactoryImpl");
System.setProperty("org.apache.poi.javax.xml.stream.XMLEventFactory", "com.fasterxml.aalto.stax.EventFactoryImpl");
```

就可以了

其它使用方式就和 poi-tl 没有任何差别了

```kotlin
    /**
     * @param path 需要保存的world的路径
     */
    fun generaWorld(path: String, map: HashMap<String, Any>?, mActivity: Context?) {
        LogUtil.v(TAG, "save world to file,map:" + LogUtil.objToString(map))

        System.setProperty("org.apache.poi.javax.xml.stream.XMLInputFactory", "com.fasterxml.aalto.stax.InputFactoryImpl");
        System.setProperty("org.apache.poi.javax.xml.stream.XMLOutputFactory", "com.fasterxml.aalto.stax.OutputFactoryImpl");
        System.setProperty("org.apache.poi.javax.xml.stream.XMLEventFactory", "com.fasterxml.aalto.stax.EventFactoryImpl");

        val inputStream = mActivity?.assets?.open("model.docx")
        if (inputStream == null) {
            LogUtil.e("can not read template file,please check assets:model.docx")
            Toast.show(mActivity?.getString(R.string.save_faild_cannot_read_file))
            return
        }

        val template = XWPFTemplate.compile(inputStream)
        map?.let {
            template.render(map)
        }
        var outputStream: FileOutputStream? = null

        try {
            outputStream = FileUtil.instant.getFileOutputStream(path)
            if (outputStream == null) {
                LogUtil.w(TAG, "world path:$path is null,check permiss")
                Toast.show(mActivity.getString(R.string.save_faild_cannot_writ))
                return
            }
            template.write(outputStream)
            outputStream.flush()
            Toast.show("save success,path:$path")
        } catch (e: IOException) {
            LogUtil.e(TAG, "world write to output stream io exception:" +
                    LogUtil.objToString(e))
            Toast.show(mActivity.getString(R.string.save_faild_cannot_writ))
        } finally {
            try {
                template.close()
                outputStream?.close()
            } finally {
                LogUtil.i(TAG, "write world to $path output stream over")
            }
        }
    }
```

**Comment by Kay-Tian** [comment]
@zwc456baby 看了你的文章尝试了一下，加入表格时报错了：
 Process: com.ocftgamma.ocr.activitys, PID: 9105
    java.lang.NoSuchMethodError: No interface method getName()Ljavax/xml/namespace/QName; in class Lorg/apache/xmlbeans/SchemaType; or its super classes (declaration of 'org.apache.xmlbeans.SchemaType' appears in /data/app/com.ocftgamma.ocr.activitys-LwUTIkdl3s14au-tBVvSnA==/split_lib_dependencies_apk.apk!classes2.dex)
        at com.deepoove.poi.NiceXWPFDocument.insertNewTable(NiceXWPFDocument.java:163)
        at com.deepoove.poi.policy.MiniTableRenderPolicy.renderTable(MiniTableRenderPolicy.java:91)
        at com.deepoove.poi.policy.MiniTableRenderPolicy.doRender(MiniTableRenderPolicy.java:73)
        at com.deepoove.poi.policy.AbstractRenderPolicy.render(AbstractRenderPolicy.java:51)
        at com.deepoove.poi.policy.SimpleTableRenderPolicy.render(SimpleTableRenderPolicy.java:61)
        at com.deepoove.poi.render.RenderAPI.doRender(RenderAPI.java:103)
        at com.deepoove.poi.render.RenderAPI.render(RenderAPI.java:72)
        at com.deepoove.poi.XWPFTemplate.render(XWPFTemplate.java:156)
        at com.ocftgamma.ocr.model.POI.WordHandle.test(WordHandle.java:43)
        at com.ocftgamma.ocr.activitys.MainActivity.detectPse(MainActivity.java:128)
        at com.ocftgamma.ocr.activitys.MainActivity.access$500(MainActivity.java:29)
        at com.ocftgamma.ocr.activitys.MainActivity$ButtonClickListener.onClick(MainActivity.java:122)
        at android.view.View.performClick(View.java:6614)
        at android.view.View.performClickInternal(View.java:6591)
        at android.view.View.access$3100(View.java:786)
        at android.view.View$PerformClick.run(View.java:25948)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6820)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
感觉是这个poi-on-android的库里面包含的org.openxmlformats.schemas是一个裁剪过的库造成的，你有遇到么？或者有什么建议么？

**Comment by zwc456baby** [comment]
> @zwc456baby 看了你的文章尝试了一下，加入表格时报错了：
> ` java.lang.NoSuchMethodError: No interface method getName()Ljavax/xml/namespace/QName; in class Lorg/apache/xmlbeans/SchemaType; or its super classes (declaration of 'org.apache.xmlbeans.SchemaType' appears in /data/app/com.ocftgamma.ocr.activitys-LwUTIkdl3s14au-tBVvSnA==/split_lib_dependencies_apk.apk!classes2.dex)
> 
> ```
>     at com.deepoove.poi.NiceXWPFDocument.insertNewTable(NiceXWPFDocument.java:163)
>     at com.deepoove.poi.policy.MiniTableRenderPolicy.renderTable(MiniTableRenderPolicy.java:91)
>     at com.deepoove.poi.policy.MiniTableRenderPolicy.doRender(MiniTableRenderPolicy.java:73)
>     at com.deepoove.poi.policy.AbstractRenderPolicy.render(AbstractRenderPolicy.java:51)
>     at com.deepoove.poi.policy.SimpleTableRenderPolicy.render(SimpleTableRenderPolicy.java:61)
>     at com.deepoove.poi.render.RenderAPI.doRender(RenderAPI.java:103)
>     at com.deepoove.poi.render.RenderAPI.render(RenderAPI.java:72)
>     at com.deepoove.poi.XWPFTemplate.render(XWPFTemplate.java:156)
>     at com.ocftgamma.ocr.model.POI.WordHandle.test(WordHandle.java:43)
>     at com.ocftgamma.ocr.activitys.MainActivity.detectPse(MainActivity.java:128)
>     at com.ocftgamma.ocr.activitys.MainActivity.access$500(MainActivity.java:29)
>     at com.ocftgamma.ocr.activitys.MainActivity$ButtonClickListener.onClick(MainActivity.java:122)
>     at android.view.View.performClick(View.java:6614)
>     at android.view.View.performClickInternal(View.java:6591)
>     at android.view.View.access$3100(View.java:786)
>     at android.view.View$PerformClick.run(View.java:25948)
>     at android.os.Handler.handleCallback(Handler.java:873)
>     at android.os.Handler.dispatchMessage(Handler.java:99)
>     at android.os.Looper.loop(Looper.java:207)
>     at android.app.ActivityThread.main(ActivityThread.java:6820)
>     at java.lang.reflect.Method.invoke(Native Method)
>     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)`
> ```
> 
> 感觉是这个poi-on-android的库里面包含的org.openxmlformats.schemas是一个裁剪过的库造成的，你有遇到么？或者有什么建议么？

我接入的时候版本是 `1.4.2` ,现在 `poi-tl` 的 release 版本已经到了 `1.6.0` 了，不确定是否版本问题，我项目中一直使用 `1.4.2` 版本，暂时未遇到什么问题

**Comment by zwc456baby** [comment]
> @zwc456baby 看了你的文章尝试了一下，加入表格时报错了：
> ` java.lang.NoSuchMethodError: No interface method getName()Ljavax/xml/namespace/QName; in class Lorg/apache/xmlbeans/SchemaType; or its super classes (declaration of 'org.apache.xmlbeans.SchemaType' appears in /data/app/com.ocftgamma.ocr.activitys-LwUTIkdl3s14au-tBVvSnA==/split_lib_dependencies_apk.apk!classes2.dex)
> 
> ```
>     at com.deepoove.poi.NiceXWPFDocument.insertNewTable(NiceXWPFDocument.java:163)
>     at com.deepoove.poi.policy.MiniTableRenderPolicy.renderTable(MiniTableRenderPolicy.java:91)
>     at com.deepoove.poi.policy.MiniTableRenderPolicy.doRender(MiniTableRenderPolicy.java:73)
>     at com.deepoove.poi.policy.AbstractRenderPolicy.render(AbstractRenderPolicy.java:51)
>     at com.deepoove.poi.policy.SimpleTableRenderPolicy.render(SimpleTableRenderPolicy.java:61)
>     at com.deepoove.poi.render.RenderAPI.doRender(RenderAPI.java:103)
>     at com.deepoove.poi.render.RenderAPI.render(RenderAPI.java:72)
>     at com.deepoove.poi.XWPFTemplate.render(XWPFTemplate.java:156)
>     at com.ocftgamma.ocr.model.POI.WordHandle.test(WordHandle.java:43)
>     at com.ocftgamma.ocr.activitys.MainActivity.detectPse(MainActivity.java:128)
>     at com.ocftgamma.ocr.activitys.MainActivity.access$500(MainActivity.java:29)
>     at com.ocftgamma.ocr.activitys.MainActivity$ButtonClickListener.onClick(MainActivity.java:122)
>     at android.view.View.performClick(View.java:6614)
>     at android.view.View.performClickInternal(View.java:6591)
>     at android.view.View.access$3100(View.java:786)
>     at android.view.View$PerformClick.run(View.java:25948)
>     at android.os.Handler.handleCallback(Handler.java:873)
>     at android.os.Handler.dispatchMessage(Handler.java:99)
>     at android.os.Looper.loop(Looper.java:207)
>     at android.app.ActivityThread.main(ActivityThread.java:6820)
>     at java.lang.reflect.Method.invoke(Native Method)
>     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)`
> ```
> 
> 感觉是这个poi-on-android的库里面包含的org.openxmlformats.schemas是一个裁剪过的库造成的，你有遇到么？或者有什么建议么？

我查看了 poi-tl 的 release，它在 `1.5.0` 开始，升级了 `poi` 组件到 4.0.0，而 `poishadow-all.jar` 只支持到了 `POI 3.17` ,所以这应当是版本兼容问题。如果确实需要使用 `poi-tl` ,建议使用 1.4.0 版本

**Comment by zwc456baby** [comment]
可以查看这个链接
https://github.com/centic9/poi-on-android/blob/master/poishadow/build.gradle

里面有这么一行

```
compile 'org.apache.poi:poi-ooxml:3.17'
```

或许可以尝试一下使其编译 4.0.0 版本

**Comment by android-taoge** [comment]
1.4.2   andorid 使用{{*experience}}    
 val textRenderData0 = TextRenderData("2016.06-2017.09-鹅厂bug部门")
 val textRenderData1 = TextRenderData("2019.10-2020.06-阿里巴巴市场总监")
 mDatas.experience =  NumbericRenderData(arrayListOf(textRenderData0, textRenderData1))  报错：
  UncaughtException detected: java.lang.NoSuchMethodError: No interface method getName()Ljavax/xml/namespace/QName; in class Lorg/apache/xmlbeans/SchemaType; or its super classes (declaration of 'org.apache.xmlbeans.SchemaType' appears in /data/app/com.ynhere.municipal-2/base.apk:classes3.dex)
        at com.deepoove.poi.NiceXWPFDocument.insertNewParagraph(NiceXWPFDocument.java:224)
        at com.deepoove.poi.policy.NumbericRenderPolicy.doRender(NumbericRenderPolicy.java:60)
        at com.deepoove.poi.policy.AbstractRenderPolicy.render(AbstractRenderPolicy.java:51)
        at com.deepoove.poi.render.RenderAPI.doRender(RenderAPI.java:103)
        at com.deepoove.poi.render.RenderAPI.render(RenderAPI.java:72)
        at com.deepoove.poi.XWPFTemplate.render(XWPFTemplate.java:156)

**Comment by android-taoge** [comment]
> 可以查看这个链接
> https://github.com/centic9/poi-on-android/blob/master/poishadow/build.gradle
> 
> 里面有这么一行
> 
> ```
> compile 'org.apache.poi:poi-ooxml:3.17'
> ```
> 
> 或许可以尝试一下使其编译 4.0.0 版本

 classpath 'org.apache.poi:poi-ooxml:4.1.2'
我试了改成4.1.1、4.1.2  都不行，报错找不到类，是不是4.0.0以上不支持啊，好烦啊，最近项目有这块需求，真的是卡了我几天了！！！！！！！！
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/poi/javax/xml/stream/XMLStreamReader;
        at org.apache.xmlbeans.XmlBeans.buildStreamToNodeMethod(XmlBeans.java:251)
        at org.apache.xmlbeans.XmlBeans.<clinit>(XmlBeans.java:138)
        at org.apache.xmlbeans.XmlBeans.typeLoaderForClassLoader(XmlBeans.java:719)
        at org.openxmlformats.schemas.spreadsheetml.x2006.main.SstDocument$Factory.getTypeLoader(Unknown Source:25)
        at org.openxmlformats.schemas.spreadsheetml.x2006.main.SstDocument$Factory.parse(Unknown Source:0)
        at org.apache.poi.xssf.model.SharedStringsTable.readFrom(SharedStringsTable.java:123)
        at org.apache.poi.xssf.model.SharedStringsTable.<init>(SharedStringsTable.java:111)
        at org.apache.poi.xssf.usermodel.-$$Lambda$CKJ44EDIO-92rB6cwbMPKp5su5A.init(Unknown Source:2)
        at org.apache.poi.ooxml.POIXMLFactory.createDocumentPart(POIXMLFactory.java:61)
        at org.apache.poi.ooxml.POIXMLDocumentPart.read(POIXMLDocumentPart.java:684)
        at org.apache.poi.ooxml.POIXMLDocument.load(POIXMLDocument.java:180)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:288)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:309)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.poi.javax.xml.stream.XMLStreamReader" on path: DexPathList[[zip file "/data/app/~~SX-9TVY48SmzQ730WFOrSw==/com.nfcrfidreader-pldQhoZN1DcENq6LURuKLg==/base.apk"],nativeLibraryDirectories=[/data/app/~~SX-9TVY48SmzQ730WFOrSw==/com.nfcrfidreader-pldQhoZN1DcENq6LURuKLg==/lib/x86, /system/lib, /system_ext/lib, /product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 65 more
2020-10-09 21:44:31.791 23949-23949/com.nfcrfidreader I/Process: Sending signal. PID: 23949 SIG: 9

**Comment by zwc456baby** [comment]
> > 可以查看这个链接
> > https://github.com/centic9/poi-on-android/blob/master/poishadow/build.gradle
> > 里面有这么一行
> > ```
> > compile 'org.apache.poi:poi-ooxml:3.17'
> > ```
> > 
> > 
> > 或许可以尝试一下使其编译 4.0.0 版本
> 
> classpath 'org.apache.poi:poi-ooxml:4.1.2'
> 我试了改成4.0.0 、4.1.1、4.1.2 重新编译jar包都不行，报错找不到类，是不是4.0.0以上不支持啊，好烦啊，最近项目有这块需求，真的是卡了我几天了！！！！！！！！
> Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/poi/javax/xml/stream/XMLStreamReader;
> at org.apache.xmlbeans.XmlBeans.buildStreamToNodeMethod(XmlBeans.java:251)
> at org.apache.xmlbeans.XmlBeans.(XmlBeans.java:138)
> at org.apache.xmlbeans.XmlBeans.typeLoaderForClassLoader(XmlBeans.java:719)
> at org.openxmlformats.schemas.spreadsheetml.x2006.main.SstDocument$Factory.getTypeLoader(Unknown Source:25)
> at org.openxmlformats.schemas.spreadsheetml.x2006.main.SstDocument$Factory.parse(Unknown Source:0)
> at org.apache.poi.xssf.model.SharedStringsTable.readFrom(SharedStringsTable.java:123)
> at org.apache.poi.xssf.model.SharedStringsTable.(SharedStringsTable.java:111)
> at org.apache.poi.xssf.usermodel.-$$Lambda$CKJ44EDIO-92rB6cwbMPKp5su5A.init(Unknown Source:2)
> at org.apache.poi.ooxml.POIXMLFactory.createDocumentPart(POIXMLFactory.java:61)
> at org.apache.poi.ooxml.POIXMLDocumentPart.read(POIXMLDocumentPart.java:684)
> at org.apache.poi.ooxml.POIXMLDocument.load(POIXMLDocument.java:180)
> at org.apache.poi.xssf.usermodel.XSSFWorkbook.(XSSFWorkbook.java:288)
> at org.apache.poi.xssf.usermodel.XSSFWorkbook.(XSSFWorkbook.java:309)
> Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.poi.javax.xml.stream.XMLStreamReader" on path: DexPathList[[zip file "/data/app/~~SX-9TVY48SmzQ730WFOrSw==/com.nfcrfidreader-pldQhoZN1DcENq6LURuKLg==/base.apk"],nativeLibraryDirectories=[/data/app/~~SX-9TVY48SmzQ730WFOrSw==/com.nfcrfidreader-pldQhoZN1DcENq6LURuKLg==/lib/x86, /system/lib, /system_ext/lib, /product/lib]]
> at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
> ... 65 more
> 2020-10-09 21:44:31.791 23949-23949/com.nfcrfidreader I/Process: Sending signal. PID: 23949 SIG: 9

如果确实需要使用这个库，还是用旧版本吧

**Comment by android-taoge** [comment]
> > > 可以查看这个链接
> > > https://github.com/centic9/poi-on-android/blob/master/poishadow/build.gradle
> > > 里面有这么一行
> > > ```
> > > compile 'org.apache.poi:poi-ooxml:3.17'
> > > ```
> > > 
> > > 
> > > 或许可以尝试一下使其编译 4.0.0 版本
> > 
> > 
> > classpath 'org.apache.poi:poi-ooxml:4.1.2'
> > 我试了改成4.0.0 、4.1.1、4.1.2 重新编译jar包都不行，报错找不到类，是不是4.0.0以上不支持啊，好烦啊，最近项目有这块需求，真的是卡了我几天了！！！！！！！！
> > Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/poi/javax/xml/stream/XMLStreamReader;
> > at org.apache.xmlbeans.XmlBeans.buildStreamToNodeMethod(XmlBeans.java:251)
> > at org.apache.xmlbeans.XmlBeans.(XmlBeans.java:138)
> > at org.apache.xmlbeans.XmlBeans.typeLoaderForClassLoader(XmlBeans.java:719)
> > at org.openxmlformats.schemas.spreadsheetml.x2006.main.SstDocument$Factory.getTypeLoader(Unknown Source:25)
> > at org.openxmlformats.schemas.spreadsheetml.x2006.main.SstDocument$Factory.parse(Unknown Source:0)
> > at org.apache.poi.xssf.model.SharedStringsTable.readFrom(SharedStringsTable.java:123)
> > at org.apache.poi.xssf.model.SharedStringsTable.(SharedStringsTable.java:111)
> > at org.apache.poi.xssf.usermodel.-$$Lambda$CKJ44EDIO-92rB6cwbMPKp5su5A.init(Unknown Source:2)
> > at org.apache.poi.ooxml.POIXMLFactory.createDocumentPart(POIXMLFactory.java:61)
> > at org.apache.poi.ooxml.POIXMLDocumentPart.read(POIXMLDocumentPart.java:684)
> > at org.apache.poi.ooxml.POIXMLDocument.load(POIXMLDocument.java:180)
> > at org.apache.poi.xssf.usermodel.XSSFWorkbook.(XSSFWorkbook.java:288)
> > at org.apache.poi.xssf.usermodel.XSSFWorkbook.(XSSFWorkbook.java:309)
> > Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.poi.javax.xml.stream.XMLStreamReader" on path: DexPathList[[zip file "/data/app/~~SX-9TVY48SmzQ730WFOrSw==/com.nfcrfidreader-pldQhoZN1DcENq6LURuKLg==/base.apk"],nativeLibraryDirectories=[/data/app/~~SX-9TVY48SmzQ730WFOrSw==/com.nfcrfidreader-pldQhoZN1DcENq6LURuKLg==/lib/x86, /system/lib, /system_ext/lib, /product/lib]]
> > at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
> > at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
> > at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
> > ... 65 more
> > 2020-10-09 21:44:31.791 23949-23949/com.nfcrfidreader I/Process: Sending signal. PID: 23949 SIG: 9
> 
> 如果确实需要使用这个库，还是用旧版本吧

现在项目中的个人履历条数不确定，需要用到列表标签{{*var}}，但是不管是旧版本还是高版本，都报一样的错，难受哦，而且还有个严重的问题，生成的.docx文件时乱码的。。。。。。。。。好希望作者整个完美支持android的库哦。。
