### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/poi/xwpf/usermodel/XWPFDocument

### ISSUE THREAD

**Issue by zenghuabin** [Sayi/poi-tl#234]
这个什么问题呀？
	public static void main(String[] args) throws Exception {
		Map<String,Object> map = new HashMap<String, Object>();
		map.put("NameDesens", "wabin");
		map.put("IdCardDesens", "1111111111111111111111111111111111111");
		XWPFTemplate template = XWPFTemplate.compile("E:/ecc/CaTest/CaTest/word_to_fdf.docx").render(map);
		FileOutputStream out = new FileOutputStream("E:\\ecc\\CaTest\\CaTest\\out_template.docx");
		template.write(out); 
		out.flush();
		out.close();
		template.close();
	}

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/poi/xwpf/usermodel/XWPFDocument
	at WordToFDF.main(WordToFDF.java:12)
Caused by: java.lang.ClassNotFoundException: org.apache.poi.xwpf.usermodel.XWPFDocument
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

**Comment by Sayi** [comment]
你应该引入了一个错误版本的poi吧。poi版本要求3.16以上。

**Comment by zenghuabin** [comment]
> 你应该引入了一个错误版本的poi吧。poi版本要求3.16以上。

我就导入了 poi-tl-1.4.2.jar 这个一个包

**Comment by Sayi** [comment]
@zenghuabin 你可以再工程的依赖里面看看具体有没有引入到poi，具体版本是多少
