### ISSUE TITLE
为什么用office2016编辑过文档之后就w:p标签不完整？

### ISSUE THREAD

**Issue by jasonqusen** [Sayi/poi-tl#264]
Caused by: org.apache.xmlbeans.XmlException: error: 元素类型 "w:p" 必须由匹配的结束标记 "</w:p>" 终止。
	at org.apache.xmlbeans.impl.store.Locale$SaxLoader.load(Locale.java:3448)
	at org.apache.xmlbeans.impl.store.Locale.parse(Locale.java:708)
	at org.apache.xmlbeans.impl.store.Locale.parseToXmlObject(Locale.java:692)
	at org.apache.xmlbeans.impl.store.Locale.parseToXmlObject(Locale.java:679)
	at org.apache.xmlbeans.impl.schema.SchemaTypeLoaderBase.parse(SchemaTypeLoaderBase.java:208)
	at org.openxmlformats.schemas.wordprocessingml.x2006.main.CTBody$Factory.parse(Unknown Source)
	at com.deepoove.poi.NiceXWPFDocument.merge(NiceXWPFDocument.java:411)
	at com.deepoove.poi.policy.DocxRenderPolicy.doRender(DocxRenderPolicy.java:52)
	at com.deepoove.poi.policy.DocxRenderPolicy.doRender(DocxRenderPolicy.java:40)
	at com.deepoove.poi.policy.AbstractRenderPolicy.render(AbstractRenderPolicy.java:115)

**Comment by jasonqusen** [comment]
1.4.0版本，没有这个问题

**Comment by jasonqusen** [comment]
NiceXWPFDocument.java
.replaceAll("<w:bookmarkEnd(\\s[A-Za-z0-9:\\s=\"]*)?/></w:p>", "");
多替换了一个 </w:p>
