### ISSUE TITLE
同一行中渲染两个超链接报错，希望得到帮助，项目需求

### ISSUE THREAD

**Issue by CodeNoobLH** [Sayi/poi-tl#331]
将超链接分行的话是可以得到效果的，目前是需要同一行放两个甚至以上的超链接（原因是因为同行会放两个照片，照片下面的描述文字可以超链接到图片本身，因为图片内容太多尺寸太小需要超链接查看），但是出现了报错。报错内容如下：
[main] INFO com.deepoove.poi.resolver.TemplateVisitor - Visit the document start...
[main] INFO com.deepoove.poi.resolver.TemplateVisitor - Visit the document end, resolve and create 37 ElementTemplates.
[main] INFO com.deepoove.poi.render.Render - Render the template file start...
省略……
[main] INFO com.deepoove.poi.render.Render - Start render TemplateName:HyperLink_二代测序质控结果, Sign: , policy:TextRenderPolicy
Exception in thread "main" com.deepoove.poi.exception.RenderException: Cannot render docx template, please check the Exception
	at com.deepoove.poi.render.Render.render(Render.java:78)
	at com.deepoove.poi.XWPFTemplate.render(XWPFTemplate.java:143)
	at cn.ml.gos.wordutils.ExportWordUtil.writeTemplates(ExportWordUtil.java:171)
	at cn.ml.gos.wordutils.ExportWordUtil.exportWord(ExportWordUtil.java:120)
	at cn.ml.gos.wordutils.Test.main(Test.java:31)
Caused by: com.deepoove.poi.exception.RenderException: Render template {{HyperLink_二代测序质控结果}} error
	at com.deepoove.poi.policy.AbstractRenderPolicy.reThrowException(AbstractRenderPolicy.java:83)
	at com.deepoove.poi.policy.AbstractRenderPolicy.render(AbstractRenderPolicy.java:67)
	at com.deepoove.poi.render.Render.doRender(Render.java:148)
	at com.deepoove.poi.render.Render.applyNormalPolicy(Render.java:104)
	at com.deepoove.poi.render.Render.render(Render.java:72)
	... 4 more
Caused by: java.lang.IndexOutOfBoundsException
	at org.apache.xmlbeans.impl.store.Xobj.insert_element_user(Xobj.java:2140)
	at org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTPImpl.insertNewHyperlink(Unknown Source)
	at com.deepoove.poi.XWPFParagraphWrapper.insertNewHyperLinkRun(XWPFParagraphWrapper.java:74)
	at com.deepoove.poi.NiceXWPFDocument.insertNewHyperLinkRun(NiceXWPFDocument.java:341)
	at com.deepoove.poi.policy.TextRenderPolicy$Helper.renderTextRun(TextRenderPolicy.java:50)
	at com.deepoove.poi.policy.TextRenderPolicy.doRender(TextRenderPolicy.java:41)
	at com.deepoove.poi.policy.AbstractRenderPolicy.render(AbstractRenderPolicy.java:64)
	... 7 more

其中at cn.ml.gos.wordutils.ExportWordUtil.writeTemplates(ExportWordUtil.java:171)指的是
XWPFTemplate template = XWPFTemplate.compile(templatesPath,builder.build()).render(datas);
望得到帮助。

**Comment by CodeNoobLH** [comment]
麻烦作者回复一下

**Comment by Sayi** [comment]
master上面已经修复了

**Comment by CodeNoobLH** [comment]
使用方法不变是吗？我不需要修改代码是吗？
