### ISSUE TITLE
SpringEL作为区块对的条件报错

### ISSUE THREAD

**Issue by shenhb** [Sayi/poi-tl#429]
poi-tl version: 1.8.2
软件：wps2019
**template.docx**:
{{?desc == null or desc == ''}}{{summary}}{{/}}

**error**:
com.deepoove.poi.exception.ResolverException: Mismatched start/end tags: No start mark found for end mark {{/}}
	at com.deepoove.poi.resolver.TemplateResolver.resolveXWPFRuns(TemplateResolver.java:165)
	at com.deepoove.poi.resolver.TemplateResolver.resolveBodyElements(TemplateResolver.java:103)
	at com.deepoove.poi.resolver.TemplateResolver.resolveDocument(TemplateResolver.java:81)
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:115)
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:94)
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:81)
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:77)
	at com.test.poitl.TestPoiToolJG.testDemo(TestPoiToolJG.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

是不是额外的jar包或环境？

**Comment by shenhb** [comment]
看了源码，SpELTest.java 要设置 elMode
![image](https://user-images.githubusercontent.com/11023124/90862036-64587980-e3bf-11ea-85e3-c01303933577.png)
