### ISSUE TITLE
文本框内使用区块报错

### ISSUE THREAD

**Issue by QianYC** [Sayi/poi-tl#442]
你好，我的模板如下：
![image](https://user-images.githubusercontent.com/29678096/92063207-2b5fd200-edcd-11ea-879c-430d7f4bb61a.png)
运行报错如下：
```
Exception in thread "main" com.deepoove.poi.exception.RenderException: Cannot render docx template, please check the Exception
	at com.deepoove.poi.render.DefaultRender.render(DefaultRender.java:69)
	at com.deepoove.poi.XWPFTemplate.render(XWPFTemplate.java:132)
	at InternshipToWord.render(InternshipToWord.java:53)
	at InternshipToWord.main(InternshipToWord.java:70)
Caused by: java.lang.ClassCastException: com.deepoove.poi.xwpf.XWPFTextboxContent cannot be cast to com.deepoove.poi.xwpf.NiceXWPFDocument
	at com.deepoove.poi.xwpf.BodyContainerFactory.getBodyContainer(BodyContainerFactory.java:36)
	at com.deepoove.poi.xwpf.BodyContainerFactory.getBodyContainer(BodyContainerFactory.java:42)
	at com.deepoove.poi.xwpf.BodyContainerFactory.getBodyContainer(BodyContainerFactory.java:46)
	at com.deepoove.poi.render.processor.AbstractIterableProcessor.visit(AbstractIterableProcessor.java:42)
	at com.deepoove.poi.render.processor.IterableProcessor.visit(IterableProcessor.java:51)
	at com.deepoove.poi.template.IterableTemplate.accept(IterableTemplate.java:32)
	at com.deepoove.poi.render.processor.DocumentProcessor.visit(DocumentProcessor.java:48)
	at com.deepoove.poi.template.IterableTemplate.accept(IterableTemplate.java:32)
	at com.deepoove.poi.render.processor.DefaultTemplateProcessor.lambda$process$0(DefaultTemplateProcessor.java:56)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.deepoove.poi.render.processor.DefaultTemplateProcessor.process(DefaultTemplateProcessor.java:56)
	at com.deepoove.poi.render.DefaultRender.renderTemplate(DefaultRender.java:82)
	at com.deepoove.poi.render.DefaultRender.render(DefaultRender.java:64)
	... 3 more
```
如果不实用文本框，就没有错，请问可以添加对文本框的支持吗？

**Comment by QianYC** [comment]
我目前的解决方法是用1*1的表格代替文本框hhhh

**Comment by Sayi** [comment]
master上已修复，随着下个版本发布。

**Comment by QianYC** [comment]
太神速辣
