### ISSUE TITLE
标签没有结束错误

### ISSUE THREAD

**Issue by johnbukaixin** [Sayi/poi-tl#538]
渲染模板时报错：
poi-tl版本：1.8.0
他报标签没有结束，可是检查过了标签是匹配的，然后没有都找出来

`com.deepoove.poi.exception.ResolverException: Mismatched start/end tags: No end iterable mark found for start mark {{?report}}{{idCard}} {{name}} {{gender}} {{birthDate}} {{result}} {{result}} {{samplingDate}} {{reportDate}} null
	at com.deepoove.poi.resolver.TemplateResolver.checkStack(TemplateResolver.java:245)
	at com.deepoove.poi.resolver.TemplateResolver.resolveBodyElements(TemplateResolver.java:117)
	at com.deepoove.poi.resolver.TemplateResolver.resolveDocument(TemplateResolver.java:82)
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:115)
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:85)
	at com.mytijian.report.service.impl.word.NucleicReportWordTemplateParser.parserWordTemplatea(NucleicReportWordTemplateParser.java:78)
	at com.mytijian.report.service.impl.word.NucleicReportServiceImpl.createReport(NucleicReportServiceImpl.java:47)
	at com.mytijian.report.service.impl.word.NucleicReportServiceImpl$$FastClassBySpringCGLIB$$c10a63c7.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at com.mytijian.origin.components.bizlog.BizLogManager.doAround(BizLogManager.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.mytijian.report.service.impl.word.NucleicReportServiceImpl$$EnhancerBySpringCGLIB$$985fdab5.createReport(<generated>)
	at com.alibaba.dubbo.common.bytecode.Wrapper65.invokeMethod(Wrapper65.java)
	at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:46)
	at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:72)
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53)
	at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:64)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:65)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:70)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:132)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:113)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:84)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:170)
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52)
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by johnbukaixin** [comment]
自己debug看了下，能渲染出来的在
`private void resolveXWPFRuns(List<XWPFRun> runs, final List<MetaTemplate> metaTemplates,
            final Deque<BlockTemplate> stack) {
        for (XWPFRun run : runs) {`
这个位置，run得出的标签是完整的，但是报以上异常的是标签"{{"和标签名字分开的，没有识别出来，想问一下是什么原因，我看poi原生读取的时候就有区别了。

**Comment by johnbukaixin** [comment]
还有模板是这样![image](https://user-images.githubusercontent.com/17828357/106343902-b2fd2e80-62e2-11eb-9ad2-60f169cc658f.png)
但是得出来的结果确实这样
![image](https://user-images.githubusercontent.com/17828357/106343926-d627de00-62e2-11eb-8b69-82765358c869.png)

**Comment by Sayi** [comment]
@johnbukaixin 能复现问题的模板发我邮箱。

**Comment by Sayi** [comment]
过期关闭。

**Comment by 1098854580** [comment]
我能不能在模板渲染的时候，把标签替换成另一个标签？
data.put(grade4Title + finalIndex.get(), "{{?sections" + count + "}}");
data.put("sections" + count , false);

**Comment by 1098854580** [comment]
能通过标签赋值成另一个标签吗？我现在是把区块对的结束标签放上去了，开始标签需要动态添加，这样能动态隐藏我不需要显示的数据
data.put(grade4Title + finalIndex.get(), "{{?sections" + count + "}}");
data.put("sections" + count , false);
