### ISSUE TITLE
POI 5.0.0, 無法使用嵌套

### ISSUE THREAD

**Issue by miragehsiao** [Sayi/poi-tl#568]
目前使用 POI 5.0.0 時，無法使用嵌套，錯誤如下：

Exception in thread "main" java.lang.NoSuchMethodError: org.openxmlformats.schemas.wordprocessingml.x2006.main.CTStyle.getDefault()Lorg/openxmlformats/schemas/wordprocessingml/x2006/main/STOnOff$Enum;
        at com.deepoove.poi.xwpf.XmlXWPFDocumentMerge.mergeStyles(XmlXWPFDocumentMerge.java:344)
        at com.deepoove.poi.xwpf.XmlXWPFDocumentMerge.createMergeableStrings(XmlXWPFDocumentMerge.java:110)   
        at com.deepoove.poi.xwpf.XmlXWPFDocumentMerge.merge(XmlXWPFDocumentMerge.java:67)
        at com.deepoove.poi.xwpf.NiceXWPFDocument.merge(NiceXWPFDocument.java:301)
        at com.deepoove.poi.policy.DocxRenderPolicy.doRender(DocxRenderPolicy.java:54)
        at com.deepoove.poi.policy.AbstractRenderPolicy.render(AbstractRenderPolicy.java:62)
        at com.deepoove.poi.render.DefaultRender.applyDocxPolicy(DefaultRender.java:115)
        at com.deepoove.poi.render.DefaultRender.renderInclude(DefaultRender.java:91)
        at com.deepoove.poi.render.DefaultRender.render(DefaultRender.java:65)
        at com.deepoove.poi.XWPFTemplate.render(XWPFTemplate.java:127)
        at com.mpinfo.ezpi.ExcelToWord.main(ExcelToWord.java:39)

**Comment by Sayi** [comment]
#625
