### ISSUE TITLE
word文档中同一行元素赋值

### ISSUE THREAD

**Issue by 15362719561** [Sayi/poi-tl#600]
再word文档中的同一行元素上定义两个变量 {{a}} {{b}}，但是会报错

**Comment by 15362719561** [comment]
Exception in thread "main" java.lang.IndexOutOfBoundsException
	at org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTRPrImpl.getRStyleArray(CTRPrImpl.java:160)
	at org.apache.poi.xwpf.usermodel.XWPFRun.getStyle(XWPFRun.java:1256)
	at com.deepoove.poi.util.StyleUtils.styleRun(StyleUtils.java:128)
	at com.deepoove.poi.resolver.RunningRunParagraph.refactorRun(RunningRunParagraph.java:102)
	at com.deepoove.poi.resolver.TemplateResolver.resolveBodyElements(TemplateResolver.java:100)
	at com.deepoove.poi.resolver.TemplateResolver.lambda$resolveBodyElements$0(TemplateResolver.java:110)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.deepoove.poi.resolver.TemplateResolver.resolveBodyElements(TemplateResolver.java:109)
	at com.deepoove.poi.resolver.TemplateResolver.resolveDocument(TemplateResolver.java:76)
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:181)
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:146)
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:103)
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:93)

**Comment by 15362719561** [comment]
ss

**Comment by iyezhou** [comment]
你好，请问是怎么解决的呢
