### ISSUE TITLE
模板编译出错

### ISSUE THREAD

**Issue by WarlingZhang** [Sayi/poi-tl#636]
java.lang.IndexOutOfBoundsException: null
	at org.apache.xmlbeans.impl.store.Xobj.removeElement(Xobj.java:2206)
	at org.apache.xmlbeans.impl.store.Xobj.remove_element(Xobj.java:2236)
	at org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTPImpl.removeR(Unknown Source)
	at com.deepoove.poi.xwpf.XWPFParagraphWrapper.removeRun(XWPFParagraphWrapper.java:349)
	at com.deepoove.poi.resolver.RunningRunParagraph.refactorRun(RunningRunParagraph.java:94)
	at com.deepoove.poi.resolver.TemplateResolver.resolveBodyElements(TemplateResolver.java:102)
	at com.deepoove.poi.resolver.TemplateResolver.resolveDocument(TemplateResolver.java:81)
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:110)

**Comment by Sayi** [comment]
用的什么版本？模板可以发我邮箱吗？

**Comment by WarlingZhang** [comment]
已发送，版本是1.9.1，1.10.0也报错

**Comment by Sayi** [comment]
```xml
<w:ins w:id="2" w:author="Zhang Warling" w:date="2021-08-10T10:00:00Z">
                <w:r w:rsidR="0052437F">
                    <w:rPr>
                        <w:rFonts w:ascii="黑体" w:eastAsia="黑体"/>
                        <w:color w:val="000000" w:themeColor="text1"/>
                        <w:sz w:val="28"/>
                        <w:szCs w:val="28"/>
                    </w:rPr>
                    <w:t>a</w:t>
                </w:r>
            </w:ins>
            <w:ins w:id="3" w:author="Zhang Warling" w:date="2021-08-10T10:01:00Z">
                <w:r w:rsidR="0052437F">
                    <w:rPr>
                        <w:rFonts w:ascii="黑体" w:eastAsia="黑体"/>
                        <w:color w:val="000000" w:themeColor="text1"/>
                        <w:sz w:val="28"/>
                        <w:szCs w:val="28"/>
                    </w:rPr>
                    <w:t>pplyNo</w:t>
                </w:r>
            </w:ins>
```

**Comment by AlexanderWang123** [comment]
你好，请问下，这个bug计划在那个版本修复？

**Comment by lii1988** [comment]
> 你好，请问下，这个bug计划在那个版本修复？

请问下，这个问题你有查到是哪种条件下触发的吗，能不能通过改模板来规避
