### ISSUE TITLE
在资源包里的模板文件无法读取

### ISSUE THREAD

**Issue by taojinjing** [Sayi/poi-tl#66]
我的模板文件放在 src/resources/poitl 目录下面，通过 springboot 启动 jar 包。

我的代码如下：
String baseTemplate = getClass().getClassLoader().getResource(BASE_TEMPLATE).getFile();
XWPFTemplate template = XWPFTemplate.compile(baseTemplate);

报错信息如下:
Caused by: com.deepoove.poi.exception.ResolverException: Cannot find the file [file:\C:\myProject\target\myProject-1.0-SNAPSHOT.jar!\BOOT-INF\classes!\poitl\template.docx]
        at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:113)
        at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:78)
        at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:74)

UT 执行时是可以正常读取的，只有在运行环境会报错。

**Comment by Sayi** [comment]
是springboot获取文件的方式有问题吧，和poitl没有联系。

XWPFTemplate还支持File和InputStream作为参数，你尝试解决下怎么获取文件这个问题。

**Comment by Sayi** [comment]
不客气。

**Comment by loong-chen** [comment]
@taojinjing  我也遇到一个问题,好像和你的类似.但我用idea阶段就开始 Failed to read zip entry source.能不能分享下你的解决方法

**Comment by taojinjing** [comment]
@loong-chen 
InputStream is = getClass().getClassLoader().getResourceAsStream(BASE_TEMPLATE);
XWPFTemplate template = XWPFTemplate.compile(is);
