### ISSUE TITLE
Caused by: java.lang.NoSuchFieldError: Factory

### ISSUE THREAD

**Issue by ifzm** [Sayi/poi-tl#737]
### Issue description
Caused by: java.lang.NoSuchFieldError: Factory
	at org.apache.poi.xwpf.usermodel.XWPFDocument.onDocumentRead(XWPFDocument.java:196) ~[poi-ooxml-5.2.0.jar:5.2.0]
	at org.apache.poi.ooxml.POIXMLDocument.load(POIXMLDocument.java:169) ~[poi-ooxml-5.2.0.jar:5.2.0]
	at org.apache.poi.xwpf.usermodel.XWPFDocument.<init>(XWPFDocument.java:159) ~[poi-ooxml-5.2.0.jar:5.2.0]
	at com.deepoove.poi.xwpf.NiceXWPFDocument.<init>(NiceXWPFDocument.java:97) ~[poi-tl-1.11.1.jar:na]
	at com.deepoove.poi.xwpf.NiceXWPFDocument.<init>(NiceXWPFDocument.java:93) ~[poi-tl-1.11.1.jar:na]
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:164) ~[poi-tl-1.11.1.jar:na]
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:132) ~[poi-tl-1.11.1.jar:na]
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:89) ~[poi-tl-1.11.1.jar:na]
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:79) ~[poi-tl-1.11.1.jar:na]

### poi-tl version
1.11.1
### Minimal test code to reproduce the issue

```java
// JDK 11
Map<String, Object> model = new HashMap<>();
model.put("branch", "xxx");
model.put("date", LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy年MM月dd日")));

XWPFTemplate template = XWPFTemplate.compile("D:\\tmp\\day.report.template.docx").render(model);
template.writeAndClose(new FileOutputStream("D:\\tmp\\test.docx"));
```

**Comment by ifzm** [comment]
我切换回 1.10.3 就能正常解析了 🤷‍♂️

**Comment by Sayi** [comment]
应该是依赖冲突了，导致找不到这个属性。
