### ISSUE TITLE
java.lang.NoSuchFieldError: Factory 

### ISSUE THREAD

**Issue by epart123** [Sayi/poi-tl#808]
### Issue description
java.lang.NoSuchFieldError: Factory
	at org.apache.poi.xwpf.usermodel.XWPFDocument.onDocumentRead(XWPFDocument.java:196)
	at org.apache.poi.ooxml.POIXMLDocument.load(POIXMLDocument.java:169)
	at org.apache.poi.xwpf.usermodel.XWPFDocument.<init>(XWPFDocument.java:159)
	at com.deepoove.poi.xwpf.NiceXWPFDocument.<init>(NiceXWPFDocument.java:100)
	at com.deepoove.poi.xwpf.NiceXWPFDocument.<init>(NiceXWPFDocument.java:96)
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:164)
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:132)
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:89)
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:79)
	at junit.test.Test1.test1(Test1.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:40)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:71)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:137)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)

### poi-tl version
1.12.0
### Minimal test code to reproduce the issue

```java
JKD8
```
### Minimal Docx template file
try {
			OfficialDocument a = OfficialDocument.dao.findById(7);
			DocInfoService.srv.setDocToModel(a);
			Map<String, Object> data = a.toMap();
			XWPFTemplate template = XWPFTemplate.compile("D:\\mywork\\me2019\\zsoa\\WebRoot\\eapdomain\\mb\\1.docx")
					.render(data);
			template.writeAndClose(new FileOutputStream("D:\\template2.docx"));
		} catch (Exception e) {

			e.printStackTrace();
		}

![image](https://user-images.githubusercontent.com/10379254/174917516-562b3e68-a9b3-4936-b950-264cfc449764.png)

**Comment by Sayi** [comment]
缺少依赖或者依赖冲突了，自己找一下。

**Comment by Andrew-Lin1368** [comment]
可以尝试把
<dependency>
	<groupId>com.deepoove</groupId>
	<artifactId>poi-tl</artifactId>
	<version>1.12.1</version>
</dependency>
放到<dependencies>标签的第一个位置，作为第一个依赖，这样Maven会优先采取poi-tl项目引用的依赖

**Comment by Andrew-Lin1368** [comment]
可以尝试将
```XML
<dependency>
    <groupId>com.deepoove</groupId>
    <artifactId>poi-tl</artifactId>
    <version>1.12.1</version>
</dependency>
```
放到pom文件`<dependencies>`标签的第一个位置，作为项目的第一个依赖，这样Maven会优先采取poi-tl项目引用的依赖
