### ISSUE TITLE
关于非Maven项目 jar包管理的 poi版本依赖冲突问题？？？

### ISSUE THREAD

**Issue by Joey-zy1024** [Sayi/poi-tl#816]
### Issue description
在springboot项目中引入
`<dependency>
          <groupId>org.apache.poi</groupId>
          <artifactId>poi</artifactId>
          <version>5.2.2</version>
      </dependency>
      <dependency>
          <groupId>org.apache.poi</groupId>
          <artifactId>poi-ooxml</artifactId>
          <version>5.2.2</version>
      </dependency>
<dependency>
          <groupId>com.deepoove</groupId>
          <artifactId>poi-tl</artifactId>
          <version>1.12.0</version>
      </dependency>`
如下jar包 就可以实现图表导出功能@

但是我的项目是旧项目
之前poi版本是4.1.1的 
升级到最新版5.2.2
![image](https://user-images.githubusercontent.com/38678002/178278210-cf967c41-eb16-4220-b12c-efaca276aa7f.png)
但是还是报各种错误

报错如下：
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
	at org.apache.poi.ooxml.POIXMLDocumentPart.<clinit>(POIXMLDocumentPart.java:56)
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:164)
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:132)
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:89)
	at com.kge.test.WordTest.main(WordTest.java:50)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more

我想请教下大佬 从4.1.1版本 升级到 5.2.2 版本具体需要哪些jar包 ？

**Comment by Sayi** [comment]
先通过maven查看需要哪些jar，然后拷贝下需要用到的包。

或者缺少什么包，找什么包。
