### ISSUE TITLE
commons-lang3 升级后，查询不到类

### ISSUE THREAD

**Issue by huaijinwoyu** [Sayi/poi-tl#826]
### Issue description
org.apache.commons，commons-lang3  升级到3.10之后。类查询不到

ClassNotFoundException:   org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream

### poi-tl version
1.12.0
### Minimal test code to reproduce the issue

```java
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/io/output/UnsynchronizedByteArrayOutputStream
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:164)
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:132)
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:120)
	at com.weilaios.app.instance.expand.x.service.WordUtil.toWord(WordUtil.java:106)
	at com.weilaios.app.instance.expand.x.service.WordUtil.main(WordUtil.java:119)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
```
### Minimal Docx template file
ClassNotFoundException

**Comment by sxaulibo** [comment]
Upgrade to 3.12.0

**Comment by huaijinwoyu** [comment]
今天试了，还是提示这个问题。3.12.0

**Comment by huaijinwoyu** [comment]
已经升级到3.12.0，问题还是会复现。是版本冲突吗？

**Comment by Sayi** [comment]
和lang没关系吧，这个类是common-io里面的，poi依赖的common-io是2.11.0版本，和你项目冲突了。

**Comment by xgj1988** [comment]
怎么解决？

**Comment by xgj1988** [comment]
如果自己的项目不能把commons-io改了（可能你自己的项目的其他框架有要搞版本的commons-io），引入以下的包吧。。
       <dependency>
            <groupId>com.guicedee.services</groupId>
            <artifactId>commons-io</artifactId>
            <version>1.2.2.1</version>
        </dependency>
