### ISSUE TITLE
word导出，经常在改动模板添加标签后，报空指针异常，可能是哪里问题那？

### ISSUE THREAD

**Issue by MulderLiu** [Sayi/poi-tl#874]
c.j.h.c.a.GlobalExceptionHandler         : 运行时异常:

java.lang.IndexOutOfBoundsException: null
	at org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTRPrImpl.getRStyleArray(CTRPrImpl.java:160) ~[poi-ooxml-lite-5.0.0.jar:?]
	at org.apache.poi.xwpf.usermodel.XWPFRun.getStyle(XWPFRun.java:1256) ~[poi-ooxml-5.0.0.jar:5.0.0]
	at com.deepoove.poi.util.StyleUtils.styleRun(StyleUtils.java:128) ~[poi-tl-1.10.0.jar:?]
	at com.deepoove.poi.resolver.RunningRunParagraph.refactorRun(RunningRunParagraph.java:128) ~[poi-tl-1.10.0.jar:?]
	at com.deepoove.poi.resolver.TemplateResolver.resolveBodyElements(TemplateResolver.java:100) ~[poi-tl-1.10.0.jar:?]
	at com.deepoove.poi.resolver.TemplateResolver.lambda$resolveBodyElements$0(TemplateResolver.java:110) ~[poi-tl-1.10.0.jar:?]
	at com.deepoove.poi.resolver.TemplateResolver$$Lambda$1195/1223264179.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_25]
	at com.deepoove.poi.resolver.TemplateResolver.resolveBodyElements(TemplateResolver.java:109) ~[poi-tl-1.10.0.jar:?]
	at com.deepoove.poi.resolver.TemplateResolver.resolveDocument(TemplateResolver.java:76) ~[poi-tl-1.10.0.jar:?]
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:181) ~[poi-tl-1.10.0.jar:?]
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:146) ~[poi-tl-1.10.0.jar:?]
	at com.deepoove.poi.XWPFTemplate.compile(XWPFTemplate.java:134) ~[poi-tl-1.10.0.jar:?]

**Comment by Sayi** [comment]
APache POI5.0.0有BUG，你需要升级下，使用最新版本的poi-tl，依赖的POI是5.2.2+
