### ISSUE TITLE
生成的doc文档转换pdf失败

### ISSUE THREAD

**Issue by ruixiu** [Sayi/poi-tl#95]
生成的doc文档：
[out_template.docx](https://github.com/Sayi/poi-tl/files/2251705/out_template.docx)
转换为pdf时报错（使用word编辑一下生成的文档是可以正常转换的）：
使用的转换工具：
```xml
<dependency>
            <groupId>fr.opensagres.xdocreport</groupId>
            <artifactId>fr.opensagres.poi.xwpf.converter.pdf</artifactId>
            <version>2.0.1</version>
</dependency>
```
代码：
```
private static void doc2pdf(InputStream is, OutputStream os) throws Exception {
        PdfOptions options = PdfOptions.create();

        PdfConverter.getInstance().convert(new XWPFDocument(is), os, options);
    }
```
异常信息：
Exception in thread "main" fr.opensagres.poi.xwpf.converter.core.XWPFConverterException: java.lang.NumberFormatException: For input string: ""
	at fr.opensagres.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:71)
	at fr.opensagres.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:39)
	at fr.opensagres.poi.xwpf.converter.core.AbstractXWPFConverter.convert(AbstractXWPFConverter.java:46)
	at com.rdzn.rdmi.contract.util.ContractDocTest.doc2pdf(ContractDocTest.java:51)
	at com.rdzn.rdmi.contract.util.ContractDocTest.main(ContractDocTest.java:43)
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.valueOf(Integer.java:740)
	at java.lang.Integer.decode(Integer.java:1197)
	at fr.opensagres.poi.xwpf.converter.core.Color.decode(Color.java:93)
	at fr.opensagres.poi.xwpf.converter.core.registry.ColorRegistry.createColor(ColorRegistry.java:45)
	at fr.opensagres.poi.xwpf.converter.core.registry.AbstractColorRegistry.internalCreateColor(AbstractColorRegistry.java:54)
	at fr.opensagres.poi.xwpf.converter.core.registry.AbstractColorRegistry.getColor(AbstractColorRegistry.java:42)
	at fr.opensagres.poi.xwpf.converter.core.utils.ColorHelper.getColor(ColorHelper.java:141)
	at fr.opensagres.poi.xwpf.converter.core.utils.ColorHelper.getColor(ColorHelper.java:108)
	at fr.opensagres.poi.xwpf.converter.core.utils.ColorHelper.getColor(ColorHelper.java:66)
	at fr.opensagres.poi.xwpf.converter.core.styles.run.RunFontColorValueProvider.getValue(RunFontColorValueProvider.java:42)
	at fr.opensagres.poi.xwpf.converter.core.styles.run.RunFontColorValueProvider.getValue(RunFontColorValueProvider.java:33)
	at fr.opensagres.poi.xwpf.converter.core.styles.run.AbstractRunValueProvider.getValueFromElement(AbstractRunValueProvider.java:77)
	at fr.opensagres.poi.xwpf.converter.core.styles.run.AbstractRunValueProvider.getValueFromElement(AbstractRunValueProvider.java:45)
	at fr.opensagres.poi.xwpf.converter.core.styles.AbstractValueProvider.internalGetValue(AbstractValueProvider.java:51)
	at fr.opensagres.poi.xwpf.converter.core.styles.AbstractValueProvider.getValue(AbstractValueProvider.java:42)
	at fr.opensagres.poi.xwpf.converter.core.styles.XWPFStylesDocument.getFontColor(XWPFStylesDocument.java:674)
	at fr.opensagres.poi.xwpf.converter.pdf.internal.PdfMapper.visitRun(PdfMapper.java:466)
	at fr.opensagres.poi.xwpf.converter.pdf.internal.PdfMapper.visitRun(PdfMapper.java:100)
	at fr.opensagres.poi.xwpf.converter.core.XWPFDocumentVisitor.visitRuns(XWPFDocumentVisitor.java:647)
	at fr.opensagres.poi.xwpf.converter.core.XWPFDocumentVisitor.visitParagraphBody(XWPFDocumentVisitor.java:467)
	at fr.opensagres.poi.xwpf.converter.core.XWPFDocumentVisitor.visitParagraph(XWPFDocumentVisitor.java:358)
	at fr.opensagres.poi.xwpf.converter.core.XWPFDocumentVisitor.visitBodyElements(XWPFDocumentVisitor.java:231)
	at fr.opensagres.poi.xwpf.converter.core.XWPFDocumentVisitor.start(XWPFDocumentVisitor.java:183)
	at fr.opensagres.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:57)
	... 4 more

**Comment by Sayi** [comment]
master上我已经解决了转PDF报错问题。

[#95 修复转PDF会报错的问题](https://github.com/Sayi/poi-tl/commit/2e408161455e21c60ba5738c1777cdccda788227)

但是看了下转换后的pdf，这个转PDF架包的实现效果不是很理想。

**Comment by doctorcy** [comment]
大神们有好的工具推荐吗

**Comment by jayknoxqu** [comment]
###用模版生成的word再用代码转pdf  出现同样的问题
###用模版生成的word再用代码转html出现同样的问题
```
compile group: 'com.deepoove', name: 'poi-tl', version: '1.4.2'
compile group: 'fr.opensagres.xdocreport', name: 'fr.opensagres.xdocreport.converter.docx.xwpf', version: '2.0.1'
```

```
Exception in thread "main" fr.opensagres.poi.xwpf.converter.core.XWPFConverterException: java.lang.NumberFormatException: For input string: ""
	at fr.opensagres.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:71)
	at fr.opensagres.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:39)
	at fr.opensagres.poi.xwpf.converter.core.AbstractXWPFConverter.convert(AbstractXWPFConverter.java:46)
```

**Comment by zenghuabin** [comment]
这个我用还是有这个错误呀

**Comment by yaojijiayou** [comment]
用Documents4j导出pdf，效果非常完美
参考：https://stackoverflow.com/questions/43363624/converting-docx-into-pdf-in-java
